#!/usr/bin/env python3
"""从当前数据库导出 bootstrap SQL（字典 / 配置脱敏 / 存储配置脱敏）。

用法（在仓库根目录）：
  python scripts/db/export_bootstrap_sql.py
"""

from __future__ import annotations

import json
import os
import sys
from datetime import date
from pathlib import Path

import psycopg


SENSITIVE_CONFIG_KEYS = {
    "auth.default_password",
    "audit_alert.webhook_secret",
    "mail.password",
}

STORAGE_SECRET_COLUMNS = {"access_key", "secret_key"}


def parse_db_url(url: str) -> str:
    """asyncpg URL → psycopg URL。"""
    if url.startswith("postgresql+asyncpg://"):
        return "postgresql://" + url.removeprefix("postgresql+asyncpg://")
    return url


def sql_literal(value, *, as_json: bool = False) -> str:
    if value is None:
        return "NULL"
    if isinstance(value, bool):
        return "TRUE" if value else "FALSE"
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return str(value)
    if isinstance(value, (dict, list)) or as_json:
        text = value if isinstance(value, str) else json.dumps(value, ensure_ascii=False)
        return "'" + text.replace("'", "''") + "'::json"
    if hasattr(value, "isoformat"):
        text = value.isoformat()
    else:
        text = str(value)
    return "'" + text.replace("'", "''") + "'"


def write_header(fh, table: str, note: str) -> None:
    today = date.today().isoformat()
    fh.write(
        f"""-- Bootstrap data for {table}
-- Generated by scripts/db/export_bootstrap_sql.py on {today}
-- {note}
-- Apply after alembic migrate on an empty (or intentionally cleared) table.

"""
    )


def export_table(
    conn: psycopg.Connection,
    *,
    table: str,
    columns: list[str],
    order_by: str,
    out_path: Path,
    note: str,
    transform_row=None,
) -> int:
    cols_sql = ", ".join(columns)
    with conn.cursor() as cur:
        cur.execute(f'SELECT {cols_sql} FROM "public"."{table}" ORDER BY {order_by}')
        rows = cur.fetchall()

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w", encoding="utf-8") as fh:
        write_header(fh, table, note)
        fh.write(f'DELETE FROM "public"."{table}";\n\n')
        if not rows:
            fh.write(f"-- no rows in {table}\n")
            return 0
        col_list = ", ".join(f'"{c}"' for c in columns)
        for row in rows:
            values = list(row)
            if transform_row:
                values = transform_row(dict(zip(columns, values)))
                values = [values[c] for c in columns]
            literals = []
            for col, v in zip(columns, values):
                literals.append(sql_literal(v, as_json=(col == "ext_json")))
            fh.write(
                f'INSERT INTO "public"."{table}" ({col_list}) VALUES ({", ".join(literals)});\n'
            )
    return len(rows)


def main() -> None:
    project_root = Path(__file__).resolve().parents[2]
    os.chdir(project_root)
    sys.path.insert(0, str(project_root))

    from app.core.config.settings import settings

    db_url = parse_db_url(settings.db.url)
    sql_dir = project_root / "scripts" / "sql"

    def mask_config(row: dict):
        if row.get("config_key") in SENSITIVE_CONFIG_KEYS:
            row["config_value"] = ""
        return row

    def mask_storage(row: dict):
        for col in STORAGE_SECRET_COLUMNS:
            if row.get(col):
                row[col] = ""
        return row

    with psycopg.connect(db_url) as conn:
        n_dict = export_table(
            conn,
            table="sys_dict",
            columns=[
                "id",
                "code",
                "label",
                "value",
                "color",
                "category",
                "parent_id",
                "status",
                "sort",
                "created_at",
                "created_by",
                "updated_at",
                "updated_by",
            ],
            order_by="sort, id",
            out_path=sql_dir / "sys_dict.sql",
            note="Full dictionary tree from local DB.",
        )
        n_cfg = export_table(
            conn,
            table="sys_config",
            columns=[
                "id",
                "config_key",
                "config_value",
                "category",
                "remark",
                "sort_code",
                "ext_json",
                "created_at",
                "created_by",
                "updated_at",
                "updated_by",
            ],
            order_by="category NULLS LAST, sort_code, id",
            out_path=sql_dir / "sys_config.sql",
            note="Sensitive values blanked: auth.default_password / mail.password / audit_alert.webhook_secret.",
            transform_row=mask_config,
        )
        n_sto = export_table(
            conn,
            table="sys_storage_config",
            columns=[
                "id",
                "name",
                "provider",
                "bucket",
                "endpoint",
                "access_key",
                "secret_key",
                "region",
                "use_ssl",
                "base_url",
                "public_path",
                "local_root",
                "is_default",
                "remark",
                "sort_code",
                "created_at",
                "created_by",
                "updated_at",
                "updated_by",
            ],
            order_by="sort_code, id",
            out_path=sql_dir / "sys_storage_config.sql",
            note="access_key / secret_key blanked.",
            transform_row=mask_storage,
        )

    print(f"wrote {sql_dir}/sys_dict.sql ({n_dict} rows)")
    print(f"wrote {sql_dir}/sys_config.sql ({n_cfg} rows)")
    print(f"wrote {sql_dir}/sys_storage_config.sql ({n_sto} rows)")


if __name__ == "__main__":
    main()
