"""
Generated by HEI code generator.
Author: Charlie
Generated at: 2026-07-23 16:28:54
"""

from typing import Annotated

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config.enums import AccountType
from app.core.response.pagination import PageData, PageQuery
from app.core.response.schema import ApiResponse, success
from app.core.schema.base import IdQuery
from app.core.security.session import SessionPayload
from app.deps.auth import get_current_session, require_account_type
from app.deps.db import get_db_session
from app.modules.message.conversation.schema import (
    ConversationMemberSchema,
    CreateDirectConversationRequest,
    MsgConversationSchema,
    MuteConversationRequest,
    PinConversationRequest,
)
from app.modules.message.conversation.service import (
    MsgConversationService,
)

admin_router = APIRouter()
portal_router = APIRouter()


# ── Portal / current-user routes ──────────────────────────────────────────────


@admin_router.get(
    "/message/conversations/my-list",
    dependencies=[Depends(require_account_type(AccountType.ADMIN))],
    response_model=ApiResponse[PageData[MsgConversationSchema]],
)
@portal_router.get(
    "/message/conversations/my-list",
    response_model=ApiResponse[PageData[MsgConversationSchema]],
)
async def my_list(
    query: Annotated[PageQuery, Depends()],
    db: Annotated[AsyncSession, Depends(get_db_session)],
    session: Annotated[SessionPayload, Depends(get_current_session)],
) -> ApiResponse[PageData[MsgConversationSchema]]:
    return success(await MsgConversationService(db).my_list(session, query))


@admin_router.get(
    "/message/conversations/detail",
    dependencies=[Depends(require_account_type(AccountType.ADMIN))],
    response_model=ApiResponse[MsgConversationSchema],
)
@portal_router.get(
    "/message/conversations/detail",
    response_model=ApiResponse[MsgConversationSchema],
)
async def portal_detail(
    query: Annotated[IdQuery, Depends()],
    db: Annotated[AsyncSession, Depends(get_db_session)],
    session: Annotated[SessionPayload, Depends(get_current_session)],
) -> ApiResponse[MsgConversationSchema]:
    return success(await MsgConversationService(db).detail(query, session))


@admin_router.post(
    "/message/conversations/create-direct",
    dependencies=[Depends(require_account_type(AccountType.ADMIN))],
    response_model=ApiResponse[MsgConversationSchema],
)
@portal_router.post(
    "/message/conversations/create-direct",
    response_model=ApiResponse[MsgConversationSchema],
)
async def create_direct(
    payload: CreateDirectConversationRequest,
    db: Annotated[AsyncSession, Depends(get_db_session)],
    session: Annotated[SessionPayload, Depends(get_current_session)],
) -> ApiResponse[MsgConversationSchema]:
    return success(await MsgConversationService(db).create_direct(payload, session))


@admin_router.post(
    "/message/conversations/mute",
    dependencies=[Depends(require_account_type(AccountType.ADMIN))],
    response_model=ApiResponse[None],
)
@portal_router.post(
    "/message/conversations/mute",
    response_model=ApiResponse[None],
)
async def mute(
    payload: MuteConversationRequest,
    db: Annotated[AsyncSession, Depends(get_db_session)],
    session: Annotated[SessionPayload, Depends(get_current_session)],
) -> ApiResponse[None]:
    await MsgConversationService(db).mute(payload, session)
    return success()


@admin_router.post(
    "/message/conversations/pin",
    dependencies=[Depends(require_account_type(AccountType.ADMIN))],
    response_model=ApiResponse[None],
)
@portal_router.post(
    "/message/conversations/pin",
    response_model=ApiResponse[None],
)
async def pin(
    payload: PinConversationRequest,
    db: Annotated[AsyncSession, Depends(get_db_session)],
    session: Annotated[SessionPayload, Depends(get_current_session)],
) -> ApiResponse[None]:
    await MsgConversationService(db).pin(payload, session)
    return success()


@admin_router.post(
    "/message/conversations/leave",
    dependencies=[Depends(require_account_type(AccountType.ADMIN))],
    response_model=ApiResponse[None],
)
@portal_router.post(
    "/message/conversations/leave",
    response_model=ApiResponse[None],
)
async def leave(
    payload: IdQuery,
    db: Annotated[AsyncSession, Depends(get_db_session)],
    session: Annotated[SessionPayload, Depends(get_current_session)],
) -> ApiResponse[None]:
    await MsgConversationService(db).leave(payload, session)
    return success()


@admin_router.post(
    "/message/conversations/mark-read",
    dependencies=[Depends(require_account_type(AccountType.ADMIN))],
    response_model=ApiResponse[None],
)
@portal_router.post(
    "/message/conversations/mark-read",
    response_model=ApiResponse[None],
)
async def mark_read(
    payload: IdQuery,
    db: Annotated[AsyncSession, Depends(get_db_session)],
    session: Annotated[SessionPayload, Depends(get_current_session)],
) -> ApiResponse[None]:
    await MsgConversationService(db).mark_read(payload, session)
    return success()
