"""
Generated by HEI code generator.
Author: Charlie
Generated at: 2026-07-23 16:28:54
"""

from datetime import datetime, timezone

from sqlalchemy import select, text
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config.enums import AccountType
from app.platform.storage.url import resolve_file_url
from app.core.exceptions.business import BusinessError, NotFoundError
from app.core.response.pagination import PageData, PageQuery, build_page
from app.core.schema.base import IdQuery, IdsRequest, to_schema, to_schema_list
from app.core.security.session import SessionPayload
from app.platform.db.transaction import transactional
from app.modules.message.conversation.repository import (
    MsgConversationRepository,
)
from app.modules.message.conversation.schema import (
    ConversationMemberSchema,
    CreateDirectConversationRequest,
    MsgConversationAdminPageQuery,
    MsgConversationCreateRequest,
    MsgConversationSchema,
    MsgConversationUpdateRequest,
    MuteConversationRequest,
    PinConversationRequest,
)
from app.modules.user.admin.repository import AdminUserProfileRepository
from app.modules.user.portal.repository import PortalUserProfileRepository


class MsgConversationService:
    def __init__(self, db: AsyncSession):
        self.db = db
        self.repo = MsgConversationRepository(db)

    def _pick_profile_repo(self, account_type: str):
        """根据账户类型返回对应的 profile 仓库"""
        if account_type == AccountType.ADMIN.value:
            return AdminUserProfileRepository(self.db)
        if account_type == AccountType.PORTAL.value:
            return PortalUserProfileRepository(self.db)
        raise BusinessError(f"Unsupported account type: {account_type}")

    async def _get_profile(self, account_type: str, account_id: str):
        repo = self._pick_profile_repo(account_type)
        return await repo.get_by_account_id(account_id)

    async def _get_profiles_batch(self, account_type: str, account_ids: list[str]) -> dict[str, object]:
        if not account_ids:
            return {}
        repo = self._pick_profile_repo(account_type)
        profiles = await repo.list_by_account_ids(list(dict.fromkeys(account_ids)))
        return {p.account_id: p for p in profiles}

    # ── Generated CRUD ─────────────────────────────────────────────────────────

    async def create(self, payload: MsgConversationCreateRequest) -> None:
        async with transactional(self.db):
            await self.repo.create(payload)

    async def update(self, payload: MsgConversationUpdateRequest) -> None:
        async with transactional(self.db):
            await self.repo.update(payload)

    async def delete(self, payload: IdsRequest) -> None:
        async with transactional(self.db):
            await self.repo.delete_many(payload.ids)

    async def detail(self, query: IdQuery, session: SessionPayload | None = None) -> MsgConversationSchema:
        conversation = await self.repo.get_required(query.id)
        schema = to_schema(MsgConversationSchema, conversation)
        members = await self.repo.list_members(query.id)
        schema.members = to_schema_list(ConversationMemberSchema, members)
        if session and schema.conversation_type == "DIRECT":
            await self._enrich_conversation_list([schema], session)
        return schema

    async def page_admin(self, query: MsgConversationAdminPageQuery) -> PageData[MsgConversationSchema]:
        items, total = await self.repo.page_admin(query)
        return build_page(query.pagination, total, to_schema_list(MsgConversationSchema, items))

    # ── Direct conversation ─────────────────────────────────────────────────────

    async def create_direct(
        self, payload: CreateDirectConversationRequest, session: SessionPayload
    ) -> MsgConversationSchema:
        """Find or create a DIRECT conversation between the current user and another user."""
        my_account_type = str(session.account_type)
        my_account_id = session.account_id

        # Generate a deterministic lock key from sorted user pair to serialize
        # concurrent creates for the same pair (prevents duplicate conversations).
        pair = sorted(
            [(my_account_type, my_account_id), (payload.account_type, payload.account_id)],
            key=lambda x: (x[0], x[1]),
        )
        lock_key_str = f"{pair[0][0]}:{pair[0][1]}:{pair[1][0]}:{pair[1][1]}"

        async with transactional(self.db):
            # Acquire advisory lock to serialize creates for this user pair
            await self.db.execute(
                text("SELECT pg_advisory_xact_lock(hashtext('direct'), hashtext(:key))"),
                {"key": lock_key_str},
            )

            existing = await self.repo.find_direct_conversation(
                my_account_type, my_account_id,
                payload.account_type, payload.account_id,
            )
            if existing:
                schema = to_schema(MsgConversationSchema, existing)
                members = await self.repo.list_members(existing.id)
                schema.members = to_schema_list(ConversationMemberSchema, members)
                return schema

            conv_request = MsgConversationCreateRequest(
                conversation_type="DIRECT",
                status="ACTIVE",
                extra={},
            )
            conversation = await self.repo.create(conv_request)
            await self.repo.add_member(conversation.id, my_account_type, my_account_id, role="OWNER")
            await self.repo.add_member(conversation.id, payload.account_type, payload.account_id, role="MEMBER")

        schema = to_schema(MsgConversationSchema, conversation)
        members = await self.repo.list_members(conversation.id)
        schema.members = to_schema_list(ConversationMemberSchema, members)
        # Dynamically set title/avatar based on current user's perspective
        await self._enrich_conversation_list([schema], session)
        return schema

    # ── My conversations ────────────────────────────────────────────────────────

    async def my_list(
        self, session: SessionPayload, page: PageQuery | None = None
    ) -> PageData[MsgConversationSchema]:
        conversations, total = await self.repo.list_my_conversations(
            str(session.account_type), session.account_id, page
        )
        schemas: list[MsgConversationSchema] = []
        for conv in conversations:
            schema = to_schema(MsgConversationSchema, conv)
            member = await self.repo.get_member(
                conv.id, str(session.account_type), session.account_id
            )
            if member:
                schema.unread_count = member.unread_count

            # Populate members list
            members = await self.repo.list_members(conv.id)
            schema.members = to_schema_list(ConversationMemberSchema, members)

            schemas.append(schema)

        # Enrich DIRECT conversations with other party's name/avatar
        await self._enrich_conversation_list(schemas, session)

        # Batch load last message preview（与前端会话列表一致：发送者：正文）
        msg_ids = [s.last_message_id for s in schemas if s.last_message_id]
        if msg_ids:
            from app.modules.message.message.model import MsgMessage
            stmt = select(MsgMessage.id, MsgMessage.content, MsgMessage.sender_name).where(
                MsgMessage.id.in_(list(dict.fromkeys(msg_ids)))
            )
            rows = list((await self.db.execute(stmt)).all())
            msg_map = {row[0]: (row[1], row[2]) for row in rows}
            for s in schemas:
                if s.last_message_id and s.last_message_id in msg_map:
                    content, sender_name = msg_map[s.last_message_id]
                    body = (content or "").strip() or "[附件]"
                    s.last_message = f"{sender_name}：{body}" if sender_name else body

        # Sort: pinned conversations first
        pinned_ids = set()
        for s in schemas:
            member = await self.repo.get_member(
                s.id, str(session.account_type), session.account_id
            )
            if member and member.is_pinned:
                pinned_ids.add(s.id)

        schemas.sort(key=lambda s: (0 if s.id in pinned_ids else 1, 0))

        if page:
            return build_page(page, total, schemas)
        return build_page(PageQuery(size=total), total, schemas)

    async def _enrich_conversation_list(
        self, schemas: list[MsgConversationSchema], session: SessionPayload
    ) -> None:
        """为 DIRECT 会话填充对方的名称和头像"""
        for schema in schemas:
            if schema.conversation_type != "DIRECT" or not schema.members:
                continue
            other = next(
                (m for m in schema.members
                 if not (m.account_type == str(session.account_type) and m.account_id == session.account_id)),
                None
            )
            if other:
                profile = await self._get_profile(other.account_type, other.account_id)
                if profile:
                    if not schema.title:
                        schema.title = getattr(profile, "nickname", None) or getattr(profile, "name", None)
                    if not schema.avatar:
                        schema.avatar = resolve_file_url(getattr(profile, "avatar", None))

    # ── Preferences ─────────────────────────────────────────────────────────────

    async def mute(self, payload: MuteConversationRequest, session: SessionPayload) -> None:
        await self.repo.set_muted(
            payload.conversation_id,
            str(session.account_type),
            session.account_id,
            payload.is_muted,
        )

    async def pin(self, payload: PinConversationRequest, session: SessionPayload) -> None:
        await self.repo.set_pinned(
            payload.conversation_id,
            str(session.account_type),
            session.account_id,
            payload.is_pinned,
        )

    # ── Member actions ──────────────────────────────────────────────────────────

    async def leave(self, query: IdQuery, session: SessionPayload) -> None:
        member = await self.repo.get_member(
            query.id, str(session.account_type), session.account_id
        )
        if member is None:
            raise NotFoundError("Conversation member not found")
        member.left_at = datetime.now(timezone.utc)
        await self.db.flush()

    async def mark_read(self, query: IdQuery, session: SessionPayload) -> None:
        await self.repo.reset_unread(
            query.id, str(session.account_type), session.account_id
        )
        await self.db.commit()
