"""
Generated by HEI code generator.
Author: Charlie
Generated at: 2026-07-23 16:28:48
"""

from typing import Annotated

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config.enums import AccountType
from app.core.response.pagination import PageData
from app.core.response.schema import ApiResponse, success
from app.core.schema.base import IdQuery, IdsRequest
from app.core.security.session import SessionPayload
from app.deps.auth import get_current_session, require_account_type, require_permission
from app.deps.db import get_db_session
from app.modules.message.terminal.schema import (
    MsgTerminalAdminPageQuery,
    MsgTerminalCreateRequest,
    MsgTerminalSchema,
    MsgTerminalUpdateRequest,
    PushTokenUpdateRequest,
    TerminalRegisterRequest,
)
from app.modules.message.terminal.service import (
    MsgTerminalService,
)

admin_router = APIRouter()
portal_router = APIRouter()


@admin_router.post(
    "/message/terminals/create",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("message:terminal:create")),
    ],
    response_model=ApiResponse[None],
)
async def create(
    payload: MsgTerminalCreateRequest,
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[None]:
    await MsgTerminalService(db).create(payload)
    return success()


@admin_router.post(
    "/message/terminals/update",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("message:terminal:update")),
    ],
    response_model=ApiResponse[None],
)
async def update(
    payload: MsgTerminalUpdateRequest,
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[None]:
    await MsgTerminalService(db).update(payload)
    return success()


@admin_router.post(
    "/message/terminals/delete",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("message:terminal:delete")),
    ],
    response_model=ApiResponse[None],
)
async def delete(
    payload: IdsRequest,
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[None]:
    await MsgTerminalService(db).delete(payload)
    return success()


@admin_router.get(
    "/message/terminals/detail",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("message:terminal:detail")),
    ],
    response_model=ApiResponse[MsgTerminalSchema],
)
async def detail(
    query: Annotated[IdQuery, Depends()],
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[MsgTerminalSchema]:
    return success(await MsgTerminalService(db).detail(query))


@admin_router.get(
    "/message/terminals/page",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("message:terminal:page")),
    ],
    response_model=ApiResponse[PageData[MsgTerminalSchema]],
)
async def page(
    query: Annotated[MsgTerminalAdminPageQuery, Depends()],
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[PageData[MsgTerminalSchema]]:
    return success(await MsgTerminalService(db).page_admin(query))


def register_current_user_routes():
    @portal_router.get(
        "/message/terminals/my-list",
        response_model=ApiResponse[list[MsgTerminalSchema]],
    )
    async def my_list(
        db: Annotated[AsyncSession, Depends(get_db_session)],
        session: Annotated[SessionPayload, Depends(get_current_session)],
    ) -> ApiResponse[list[MsgTerminalSchema]]:
        return success(await MsgTerminalService(db).my_list(session))

    @portal_router.post(
        "/message/terminals/register",
        response_model=ApiResponse[MsgTerminalSchema],
    )
    async def register(
        payload: TerminalRegisterRequest,
        db: Annotated[AsyncSession, Depends(get_db_session)],
        session: Annotated[SessionPayload, Depends(get_current_session)],
    ) -> ApiResponse[MsgTerminalSchema]:
        return success(await MsgTerminalService(db).register(payload, session))

    @portal_router.post(
        "/message/terminals/unregister",
        response_model=ApiResponse[None],
    )
    async def unregister(
        payload: IdsRequest,
        db: Annotated[AsyncSession, Depends(get_db_session)],
        session: Annotated[SessionPayload, Depends(get_current_session)],
    ) -> ApiResponse[None]:
        await MsgTerminalService(db).unregister(payload.ids[0], session)
        return success()

    @portal_router.post(
        "/message/terminals/update-push-token",
        response_model=ApiResponse[None],
    )
    async def update_push_token(
        payload: PushTokenUpdateRequest,
        db: Annotated[AsyncSession, Depends(get_db_session)],
        session: Annotated[SessionPayload, Depends(get_current_session)],
    ) -> ApiResponse[None]:
        await MsgTerminalService(db).update_push_token(payload, session)
        return success()


register_current_user_routes()
