"""
Generated by HEI code generator.
Author: Charlie
Generated at: 2026-07-23 16:28:48
"""

from datetime import datetime
from typing import Any

from pydantic import Field

from app.core.response.pagination import PageQuery
from app.core.schema.base import ApiSchema


class MsgTerminalCreateRequest(ApiSchema):
    account_type: str
    account_id: str
    device_type: str
    device_name: str | None = None
    device_id: str | None = None
    push_token: str | None = None
    push_provider: str | None = None
    app_version: str | None = None
    is_online: bool
    last_online_at: datetime | None = None
    last_login_at: datetime
    extra: dict[str, Any]


class MsgTerminalUpdateRequest(MsgTerminalCreateRequest):
    id: str = Field(min_length=1, max_length=64)


class MsgTerminalAdminPageQuery(PageQuery):
    keyword: str | None = None


class TerminalRegisterRequest(ApiSchema):
    device_type: str
    device_name: str | None = None
    device_id: str | None = None
    app_version: str | None = None


class PushTokenUpdateRequest(ApiSchema):
    id: str = Field(min_length=1, max_length=64)
    push_token: str | None = None
    push_provider: str | None = None


class MsgTerminalSchema(ApiSchema):
    id: str
    account_type: str
    account_id: str
    device_type: str
    device_name: str | None = None
    device_id: str | None = None
    push_token: str | None = None
    push_provider: str | None = None
    app_version: str | None = None
    is_online: bool
    last_online_at: datetime | None = None
    last_login_at: datetime
    extra: dict[str, Any]
    created_at: datetime
    created_by: str | None = None
    updated_at: datetime
    updated_by: str | None = None
