"""
Generated by HEI code generator.
Author: Charlie
Generated at: 2026-07-23 16:28:52
"""

from datetime import datetime, timezone

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.exceptions.business import BusinessError
from app.core.response.pagination import PageData, build_page
from app.core.schema.base import IdQuery, IdsRequest, to_schema, to_schema_list
from app.core.security.session import SessionPayload
from app.platform.db.transaction import transactional
from app.platform.storage.url import resolve_file_url
from app.modules.message.enums import (
    ConversationMemberRole,
    ConversationStatus,
    ConversationType,
    GroupJoinRequestStatus,
    GroupStatus,
)
from app.modules.message.group.model import (
    MsgGroupJoinRequest,
    MsgGroupMember,
)
from app.modules.message.group.repository import (
    MsgGroupRepository,
)
from app.modules.message.group.schema import (
    GroupCreateRequest,
    GroupJoinRequestCreate,
    GroupJoinRequestHandle,
    GroupJoinRequestSchema,
    GroupMemberAddRequest,
    GroupMemberListRequest,
    GroupMemberRemoveRequest,
    GroupMemberSchema,
    GroupSearchQuery,
    GroupUpdateRequest,
    GroupDetailRequest,
    SetMemberRoleRequest,
    MsgGroupAdminPageQuery,
    MsgGroupCreateRequest,
    MsgGroupSchema,
    MsgGroupUpdateRequest,
)
from app.platform.id_generator.snowflake import generate_snowflake_id


class MsgGroupService:
    def __init__(self, db: AsyncSession):
        self.db = db
        self.repo = MsgGroupRepository(db)

    # ==================== Admin CRUD ====================

    async def create(self, payload: MsgGroupCreateRequest) -> None:
        async with transactional(self.db):
            await self.repo.create(payload)

    async def update(self, payload: MsgGroupUpdateRequest) -> None:
        async with transactional(self.db):
            await self.repo.update(payload)

    async def delete(self, payload: IdsRequest) -> None:
        async with transactional(self.db):
            await self.repo.delete_many(payload.ids)

    async def detail(self, query: IdQuery) -> MsgGroupSchema:
        return to_schema(MsgGroupSchema, await self.repo.get_required(query.id))

    async def page_admin(self, query: MsgGroupAdminPageQuery) -> PageData[MsgGroupSchema]:
        items, total = await self.repo.page_admin(query)
        return build_page(query.pagination, total, to_schema_list(MsgGroupSchema, items))

    # ==================== Current-User Group Management ====================

    async def create_group(self, payload: GroupCreateRequest, session: SessionPayload) -> MsgGroupSchema:
        """Create a group: create MsgGroup + add owner as member + auto-create conversation."""
        async with transactional(self.db):
            group = await self.repo.create(
                MsgGroupCreateRequest(
                    name=payload.name,
                    avatar=payload.avatar,
                    description=payload.description,
                    owner_account_type=str(session.account_type),
                    owner_account_id=session.account_id,
                    status=GroupStatus.ENABLED.value,
                    join_mode=payload.join_mode,
                    max_members=payload.max_members,
                    member_count=1,
                    extra={},
                )
            )
            # Add owner as member
            await self.repo.add_member(
                group_id=group.id,
                account_type=str(session.account_type),
                account_id=session.account_id,
                role=ConversationMemberRole.OWNER.value,
            )
            # Auto-create conversation
            await self._create_group_conversation(group.id, payload.name, session)

        return to_schema(MsgGroupSchema, group)

    async def update_group(self, payload: GroupUpdateRequest, session: SessionPayload) -> MsgGroupSchema:
        """Update group info. Only the owner can update."""
        async with transactional(self.db):
            if not await self.repo.is_owner(
                payload.id, str(session.account_type), session.account_id
            ):
                raise BusinessError("Only the group owner can update group info")

            group = await self.repo.update_group_fields(
                group_id=payload.id,
                name=payload.name,
                avatar=payload.avatar,
                description=payload.description,
                join_mode=payload.join_mode,
                max_members=payload.max_members,
            )
        return to_schema(MsgGroupSchema, group)

    async def dissolve(self, payload: GroupDetailRequest, session: SessionPayload) -> None:
        """Dissolve a group. Only the owner can dissolve."""
        group_id = payload.id
        async with transactional(self.db):
            if not await self.repo.is_owner(
                group_id, str(session.account_type), session.account_id
            ):
                raise BusinessError("Only the group owner can dissolve the group")

            await self.repo.update_group_fields(
                group_id=group_id, status=GroupStatus.DISSOLVED.value
            )
            # Mark conversation as disabled
            await self._disable_group_conversation(group_id)

    async def leave(self, payload: GroupDetailRequest, session: SessionPayload) -> None:
        """Leave a group. The owner cannot leave."""
        group_id = payload.id
        account_type = str(session.account_type)
        account_id = session.account_id

        if await self.repo.is_owner(group_id, account_type, account_id):
            raise BusinessError("Owner cannot leave the group. Dissolve or transfer ownership first.")

        member = await self.repo.get_member(group_id, account_type, account_id)
        if member is None:
            raise BusinessError("You are not a member of this group")

        async with transactional(self.db):
            await self.repo.remove_member(group_id, account_type, account_id)
            await self.repo.decrement_member_count(group_id)
            await self._remove_member_from_conversation(group_id, account_type, account_id)

    async def my_list(self, session: SessionPayload) -> list[MsgGroupSchema]:
        """List my groups with member_count and pending request count."""
        account_type = str(session.account_type)
        account_id = session.account_id

        groups = await self.repo.list_my_groups(account_type, account_id)
        schemas = to_schema_list(MsgGroupSchema, groups)
        return schemas

    async def search_groups(
        self, query: GroupSearchQuery, session: SessionPayload
    ) -> list[MsgGroupSchema]:
        """Search groups by name; mark membership / pending apply for UI states."""
        keyword = query.keyword
        account_type = str(session.account_type)
        account_id = session.account_id
        my_groups = await self.repo.list_my_groups(account_type, account_id)
        member_ids = {g.id for g in my_groups}
        my_reqs = await self.repo.list_my_join_requests(account_type, account_id)
        pending_ids = {
            r.group_id
            for r in my_reqs
            if r.status == GroupJoinRequestStatus.PENDING.value
        }
        groups = await self.repo.search_groups(keyword, exclude_group_ids=[])
        result: list[MsgGroupSchema] = []
        for g in groups:
            schema = to_schema(MsgGroupSchema, g)
            schema.is_member = g.id in member_ids
            schema.has_pending_request = g.id in pending_ids
            result.append(schema)
        return result

    async def group_detail(self, query: IdQuery, session: SessionPayload) -> MsgGroupSchema:
        """Get group detail. Verifies the user is a member."""
        group_id = query.id
        account_type = str(session.account_type)
        account_id = session.account_id

        group = await self.repo.get_required(group_id)
        member = await self.repo.get_member(group_id, account_type, account_id)
        if member is None:
            raise BusinessError("You are not a member of this group")
        return to_schema(MsgGroupSchema, group)

    # ==================== Group Members ====================

    async def list_members(
        self, query: IdQuery, session: SessionPayload
    ) -> list[GroupMemberSchema]:
        """List group members with profile info (name/avatar). Batch load profiles."""
        group_id = query.id
        members = await self.repo.list_members(group_id)
        if not members:
            return []

        admin_ids = []
        portal_ids = []
        for m in members:
            (admin_ids if m.account_type == "ADMIN" else portal_ids).append(m.account_id)
        admin_profiles = await self._get_profiles_batch("ADMIN", admin_ids) if admin_ids else {}
        portal_profiles = await self._get_profiles_batch("PORTAL", portal_ids) if portal_ids else {}

        schemas = []
        for m in members:
            schema = to_schema(GroupMemberSchema, m)
            profiles = admin_profiles if m.account_type == "ADMIN" else portal_profiles
            profile = profiles.get(m.account_id)
            if profile:
                schema.profile_name = profile.name or profile.nickname
                schema.profile_avatar = resolve_file_url(profile.avatar)
            schemas.append(schema)
        return schemas

    async def add_members(
        self, payload: GroupMemberAddRequest, session: SessionPayload
    ) -> None:
        """Add members to a group. Only owner/admin can do this."""
        async with transactional(self.db):
            if not await self.repo.is_owner_or_admin(
                payload.group_id, str(session.account_type), session.account_id
            ):
                raise BusinessError("Only owner or admin can add members")

            group = await self.repo.get_required(payload.group_id)
            count = len(payload.members)
            if group.member_count + count > group.max_members:
                raise BusinessError("Group is full")

            member_tuples = [
                (m["account_type"], m["account_id"])
                for m in payload.members
            ]
            await self.repo.add_members_batch(payload.group_id, member_tuples)
            await self.repo.increment_member_count(payload.group_id, delta=count)

            # Also add members to the conversation
            for acct_type, acct_id in member_tuples:
                await self._add_member_to_conversation(
                    payload.group_id, acct_type, acct_id, role="MEMBER"
                )

    async def remove_members(
        self, payload: GroupMemberRemoveRequest, session: SessionPayload
    ) -> None:
        """Remove a member from a group. Only owner/admin can do this."""
        async with transactional(self.db):
            if not await self.repo.is_owner_or_admin(
                payload.group_id, str(session.account_type), session.account_id
            ):
                raise BusinessError("Only owner or admin can remove members")

            # Cannot remove the group owner
            group = await self.repo.get_required(payload.group_id)
            if (
                group.owner_account_type == payload.account_type
                and group.owner_account_id == payload.account_id
            ):
                raise BusinessError("Cannot remove the group owner")

            member = await self.repo.get_member(
                payload.group_id, payload.account_type, payload.account_id
            )
            if member is None:
                raise BusinessError("User is not a member of this group")

            await self.repo.remove_member(
                payload.group_id, payload.account_type, payload.account_id
            )
            await self.repo.decrement_member_count(payload.group_id)
            await self._remove_member_from_conversation(
                payload.group_id, payload.account_type, payload.account_id,
            )

    async def set_member_role(
        self, payload: SetMemberRoleRequest, session: SessionPayload
    ) -> None:
        """Set a member's role. Only owner can change roles."""
        async with transactional(self.db):
            if not await self.repo.is_owner(
                payload.group_id, str(session.account_type), session.account_id
            ):
                raise BusinessError("Only the group owner can set member roles")

            member = await self.repo.get_member(
                payload.group_id, payload.account_type, payload.account_id
            )
            if member is None:
                raise BusinessError("User is not a member of this group")

            await self.repo.update_member_role(
                payload.group_id, payload.account_type, payload.account_id, payload.role
            )

    # ==================== Group Join Requests ====================

    async def apply_join(
        self, payload: GroupJoinRequestCreate, session: SessionPayload
    ) -> None:
        """Apply to join a group（已是成员 / 已有待处理申请时幂等成功）。"""
        group = await self.repo.get_required(payload.group_id)
        if group.status == GroupStatus.DISSOLVED.value:
            raise BusinessError("Group has been dissolved")

        account_type = str(session.account_type)
        account_id = session.account_id

        existing_member = await self.repo.get_member(
            payload.group_id, account_type, account_id
        )
        if existing_member is not None:
            return

        existing_pending = await self.repo.get_pending_join_request(
            payload.group_id, account_type, account_id
        )
        if existing_pending is not None:
            return

        created_or_reactivated = False
        request = None

        async with transactional(self.db):
            existing_any = await self.repo.get_any_join_request(
                payload.group_id, account_type, account_id
            )
            if existing_any is not None:
                if existing_any.status == GroupJoinRequestStatus.ACCEPTED.value:
                    return
                # REJECTED → 允许重新申请
                existing_any.status = GroupJoinRequestStatus.PENDING.value
                existing_any.message = payload.message
                existing_any.handled_by_type = None
                existing_any.handled_by_id = None
                existing_any.handled_at = None
                await self.db.flush()
                request = existing_any
                created_or_reactivated = True
            else:
                request = await self.repo.create_join_request(
                    group_id=payload.group_id,
                    applicant_type=account_type,
                    applicant_id=account_id,
                    message=payload.message,
                )
                created_or_reactivated = True

        if created_or_reactivated and request is not None:
            try:
                await self._push_join_request_created(
                    request, payload, account_type, account_id, group.name,
                )
            except Exception:
                pass

    async def handle_join_request(
        self, payload: GroupJoinRequestHandle, session: SessionPayload
    ) -> None:
        """Handle a join request (accept/reject). Only owner/admin can handle."""
        async with transactional(self.db):
            join_request = await self.repo.get_join_request_by_id(payload.id)
            if join_request is None:
                raise BusinessError("Join request not found")
            if join_request.status != GroupJoinRequestStatus.PENDING.value:
                raise BusinessError("Join request has already been handled")

            group = await self.repo.get_required(join_request.group_id)

            if not await self.repo.is_owner_or_admin(
                join_request.group_id, str(session.account_type), session.account_id
            ):
                raise BusinessError("Only owner or admin can handle join requests")

            now = datetime.now(timezone.utc)
            join_request.status = payload.status
            join_request.handled_by_type = str(session.account_type)
            join_request.handled_by_id = session.account_id
            join_request.handled_at = now

            if payload.status == GroupJoinRequestStatus.ACCEPTED.value:
                # Check if already a member
                existing_member = await self.repo.get_member(
                    join_request.group_id,
                    join_request.applicant_type,
                    join_request.applicant_id,
                )
                if existing_member is None:
                    if group.member_count + 1 > group.max_members:
                        raise BusinessError("Group is full, cannot accept this request")
                    await self.repo.add_member(
                        group_id=join_request.group_id,
                        account_type=join_request.applicant_type,
                        account_id=join_request.applicant_id,
                    )
                    await self.repo.increment_member_count(join_request.group_id)
                    # Also add to conversation
                    await self._add_member_to_conversation(
                        join_request.group_id,
                        join_request.applicant_type,
                        join_request.applicant_id,
                        role="MEMBER",
                    )

            await self.db.flush()

        # Push WS notification to applicant about the result
        try:
            from app.modules.message.websocket.handler import manager as ws_manager
            ws_payload = {
                "type": "join_request_handled",
                "data": {
                    "request_id": join_request.id,
                    "group_id": group.id,
                    "group_name": group.name,
                    "status": payload.status,
                },
            }
            await ws_manager.route_to_user(
                join_request.applicant_type,
                join_request.applicant_id,
                ws_payload,
            )
        except Exception:
            pass

    async def _push_join_request_created(
        self,
        request: object,
        payload: object,
        account_type: str,
        account_id: str,
        group_name: str | None = None,
    ) -> None:
        """Push a new join request notification to group owners/admins via WebSocket."""
        from app.modules.message.websocket.handler import manager as ws_manager

        try:
            profile = await self._get_profile(account_type, account_id)
        except Exception:
            profile = None

        ws_payload = {
            "type": "new_join_request",
            "data": {
                "id": request.id,
                "group_id": payload.group_id,
                "applicant_type": account_type,
                "applicant_id": account_id,
                "message": payload.message,
                "status": "PENDING",
                "created_at": (request.created_at.isoformat() if hasattr(request, 'created_at') and request.created_at else None),
                "applicant_name": profile.name if profile else None,
                "applicant_avatar": profile.avatar if profile else None,
                "group_name": group_name,
            },
        }

        members = await self.repo.list_members(payload.group_id)
        for member in members:
            if member.role in ("OWNER", "ADMIN"):
                try:
                    await ws_manager.route_to_user(
                        member.account_type, member.account_id, ws_payload
                    )
                except Exception:
                    pass

    async def my_join_requests(
        self, session: SessionPayload
    ) -> list[GroupJoinRequestSchema]:
        """List my join requests with profile and group info."""
        requests = await self.repo.list_my_join_requests(
            str(session.account_type), session.account_id
        )
        return await self._enrich_join_requests(requests)

    async def pending_requests(
        self, session: SessionPayload
    ) -> list[GroupJoinRequestSchema]:
        """List pending join requests for groups I own/admin."""
        account_type = str(session.account_type)
        account_id = session.account_id

        my_groups = await self.repo.list_my_groups(account_type, account_id)
        managed_group_ids = [
            g.id for g in my_groups
            if g.owner_account_type == account_type and g.owner_account_id == account_id
        ]
        # Also include groups where I am admin
        stmt = select(MsgGroupMember.group_id).where(
            MsgGroupMember.account_type == account_type,
            MsgGroupMember.account_id == account_id,
            MsgGroupMember.left_at.is_(None),
            MsgGroupMember.role.in_([
                ConversationMemberRole.OWNER.value,
                ConversationMemberRole.ADMIN.value,
            ]),
        )
        rows = list((await self.db.execute(stmt)).scalars().all())
        managed_group_ids = list(set(managed_group_ids + rows))

        if not managed_group_ids:
            return []

        requests = await self.repo.list_pending_requests(managed_group_ids)
        return await self._enrich_join_requests(requests)

    async def pending_count(self, session: SessionPayload) -> int:
        """Get count of pending join requests for groups I manage."""
        account_type = str(session.account_type)
        account_id = session.account_id

        stmt = (
            select(MsgGroupMember.group_id)
            .where(
                MsgGroupMember.account_type == account_type,
                MsgGroupMember.account_id == account_id,
                MsgGroupMember.left_at.is_(None),
                MsgGroupMember.role.in_([
                    ConversationMemberRole.OWNER.value,
                    ConversationMemberRole.ADMIN.value,
                ]),
            )
        )
        rows = list((await self.db.execute(stmt)).scalars().all())
        managed_group_ids = list(set(rows))

        if not managed_group_ids:
            return 0

        counts = await self.repo.count_pending_requests(managed_group_ids)
        return sum(counts.values())

    # ==================== Private Helpers ====================

    async def _enrich_join_requests(
        self, requests: list[MsgGroupJoinRequest]
    ) -> list[GroupJoinRequestSchema]:
        """Enrich join requests with applicant name/avatar and group name (batch)."""
        if not requests:
            return []

        admin_ids = []
        portal_ids = []
        group_ids = set()
        for req in requests:
            (admin_ids if req.applicant_type == "ADMIN" else portal_ids).append(req.applicant_id)
            group_ids.add(req.group_id)

        admin_profiles = await self._get_profiles_batch("ADMIN", admin_ids) if admin_ids else {}
        portal_profiles = await self._get_profiles_batch("PORTAL", portal_ids) if portal_ids else {}

        group_names = {}
        if group_ids:
            from sqlalchemy import select
            from app.modules.message.group.model import MsgGroup
            stmt = select(MsgGroup.id, MsgGroup.name).where(MsgGroup.id.in_(list(group_ids)))
            rows = (await self.db.execute(stmt)).all()
            group_names = {str(r[0]): str(r[1]) for r in rows}

        schemas = []
        for req in requests:
            schema = to_schema(GroupJoinRequestSchema, req)
            profiles = admin_profiles if req.applicant_type == "ADMIN" else portal_profiles
            profile = profiles.get(req.applicant_id)
            if profile:
                schema.applicant_name = profile.name or profile.nickname
                schema.applicant_avatar = resolve_file_url(profile.avatar)
            schema.group_name = group_names.get(req.group_id)
            schemas.append(schema)
        return schemas

    async def _get_profile(self, account_type: str, account_id: str):
        """Legacy single-profile lookup. Use _get_profiles_batch for N+1 safety."""
        from app.modules.user.admin.model import AdminUserProfile
        from app.modules.user.portal.model import PortalUserProfile

        model = AdminUserProfile if account_type == "ADMIN" else PortalUserProfile
        stmt = select(model).where(model.account_id == account_id)
        return (await self.db.execute(stmt)).scalar_one_or_none()

    async def _get_profiles_batch(self, account_type: str, account_ids: list[str]) -> dict[str, object]:
        """Batch load profiles by account type. Returns {account_id: profile}."""
        if not account_ids:
            return {}
        from app.modules.user.admin.model import AdminUserProfile
        from app.modules.user.portal.model import PortalUserProfile
        model = AdminUserProfile if account_type == "ADMIN" else PortalUserProfile
        stmt = select(model).where(model.account_id.in_(list(dict.fromkeys(account_ids))))
        rows = list((await self.db.execute(stmt)).scalars().all())
        return {p.account_id: p for p in rows}

    async def _create_group_conversation(
        self, group_id: str, group_name: str, session: SessionPayload
    ) -> None:
        """Create a conversation for the group and add the creator as a member."""
        from app.modules.message.conversation.model import MsgConversation, MsgConversationMember
        from datetime import datetime, timezone

        conversation = MsgConversation(
            conversation_type=ConversationType.GROUP.value,
            title=group_name,
            group_id=group_id,
            owner_account_type=str(session.account_type),
            owner_account_id=session.account_id,
            status=ConversationStatus.ACTIVE.value,
        )
        self.db.add(conversation)
        await self.db.flush()

        # Add the group creator as a conversation member
        member = MsgConversationMember(
            conversation_id=conversation.id,
            account_type=str(session.account_type),
            account_id=session.account_id,
            role=ConversationMemberRole.OWNER.value,
            joined_at=datetime.now(timezone.utc),
        )
        self.db.add(member)
        await self.db.flush()

    async def _get_group_conversation(self, group_id: str):
        """Get the active group conversation for a group, or None."""
        from app.modules.message.conversation.model import MsgConversation

        stmt = select(MsgConversation).where(
            MsgConversation.group_id == group_id,
            MsgConversation.conversation_type == ConversationType.GROUP.value,
            MsgConversation.status == ConversationStatus.ACTIVE.value,
        )
        return (await self.db.execute(stmt)).scalar_one_or_none()

    async def _add_member_to_conversation(
        self, group_id: str, account_type: str, account_id: str, role: str = "MEMBER"
    ) -> None:
        """Add a user to the group's active conversation if not already a member."""
        from app.modules.message.conversation.model import MsgConversationMember
        from datetime import datetime, timezone

        conversation = await self._get_group_conversation(group_id)
        if conversation is None:
            return

        existing = select(MsgConversationMember).where(
            MsgConversationMember.conversation_id == conversation.id,
            MsgConversationMember.account_type == account_type,
            MsgConversationMember.account_id == account_id,
            MsgConversationMember.left_at.is_(None),
        )
        if (await self.db.execute(existing)).scalar_one_or_none() is not None:
            return

        member = MsgConversationMember(
            conversation_id=conversation.id,
            account_type=account_type,
            account_id=account_id,
            role=role,
            joined_at=datetime.now(timezone.utc),
        )
        self.db.add(member)

    async def _remove_member_from_conversation(
        self, group_id: str, account_type: str, account_id: str
    ) -> None:
        """Remove a user from the group's conversation (soft-delete via left_at)."""
        from app.modules.message.conversation.model import MsgConversation

        stmt = select(MsgConversation).where(
            MsgConversation.group_id == group_id,
            MsgConversation.conversation_type == ConversationType.GROUP.value,
        )
        conversation = (await self.db.execute(stmt)).scalar_one_or_none()
        if conversation is None:
            return

        from app.modules.message.conversation.repository import MsgConversationRepository
        await MsgConversationRepository(self.db).remove_member(
            conversation.id, account_type, account_id
        )

    async def _disable_group_conversation(self, group_id: str) -> None:
        """Mark the group's conversation as disabled."""
        from app.modules.message.conversation.model import MsgConversation

        stmt = select(MsgConversation).where(
            MsgConversation.group_id == group_id,
            MsgConversation.conversation_type == ConversationType.GROUP.value,
        )
        conversation = (await self.db.execute(stmt)).scalar_one_or_none()
        if conversation:
            conversation.status = ConversationStatus.DISABLED.value
            await self.db.flush()
