"""
Generated by HEI code generator.
Author: Charlie
Generated at: 2026-07-23 16:28:53
"""

from typing import Annotated

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config.enums import AccountType
from app.core.response.schema import ApiResponse, success
from app.core.security.session import SessionPayload
from app.deps.auth import get_current_session, require_account_type
from app.deps.db import get_db_session
from app.modules.message.friend.schema import (
    ApplyFriendRequest,
    FriendRequestSchema,
    FriendSchema,
    FriendSearchQuery,
    HandleFriendRequest,
    MyRequestCountSchema,
    RemoveFriendRequest,
    SearchUserSchema,
    SetRemarkRequest,
)
from app.modules.message.friend.service import (
    MsgFriendService,
)

admin_router = APIRouter()
portal_router = APIRouter()


# ── Current-user routes (admin + portal) ────────────────────────────────────


@admin_router.get(
    "/message/friends/my-list",
    dependencies=[Depends(require_account_type(AccountType.ADMIN))],
    response_model=ApiResponse[list[FriendSchema]],
)
@portal_router.get(
    "/message/friends/my-list",
    dependencies=[Depends(require_account_type(AccountType.PORTAL))],
    response_model=ApiResponse[list[FriendSchema]],
)
async def my_list(
    session: Annotated[SessionPayload, Depends(get_current_session)],
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[list[FriendSchema]]:
    return success(await MsgFriendService(db).my_list(session))


@admin_router.get(
    "/message/friends/search",
    dependencies=[Depends(require_account_type(AccountType.ADMIN))],
    response_model=ApiResponse[list[SearchUserSchema]],
)
@portal_router.get(
    "/message/friends/search",
    dependencies=[Depends(require_account_type(AccountType.PORTAL))],
    response_model=ApiResponse[list[SearchUserSchema]],
)
async def search(
    session: Annotated[SessionPayload, Depends(get_current_session)],
    db: Annotated[AsyncSession, Depends(get_db_session)],
    query: Annotated[FriendSearchQuery, Depends()],
) -> ApiResponse[list[SearchUserSchema]]:
    return success(await MsgFriendService(db).search(query, session))


@admin_router.post(
    "/message/friends/apply",
    dependencies=[Depends(require_account_type(AccountType.ADMIN))],
    response_model=ApiResponse[None],
)
@portal_router.post(
    "/message/friends/apply",
    dependencies=[Depends(require_account_type(AccountType.PORTAL))],
    response_model=ApiResponse[None],
)
async def apply(
    payload: ApplyFriendRequest,
    session: Annotated[SessionPayload, Depends(get_current_session)],
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[None]:
    await MsgFriendService(db).apply(payload, session)
    return success()


@admin_router.post(
    "/message/friends/handle-request",
    dependencies=[Depends(require_account_type(AccountType.ADMIN))],
    response_model=ApiResponse[None],
)
@portal_router.post(
    "/message/friends/handle-request",
    dependencies=[Depends(require_account_type(AccountType.PORTAL))],
    response_model=ApiResponse[None],
)
async def handle_request(
    payload: HandleFriendRequest,
    session: Annotated[SessionPayload, Depends(get_current_session)],
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[None]:
    await MsgFriendService(db).handle_request(payload, session)
    return success()


@admin_router.post(
    "/message/friends/remove",
    dependencies=[Depends(require_account_type(AccountType.ADMIN))],
    response_model=ApiResponse[None],
)
@portal_router.post(
    "/message/friends/remove",
    dependencies=[Depends(require_account_type(AccountType.PORTAL))],
    response_model=ApiResponse[None],
)
async def remove(
    payload: RemoveFriendRequest,
    session: Annotated[SessionPayload, Depends(get_current_session)],
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[None]:
    await MsgFriendService(db).remove(payload, session)
    return success()


@admin_router.post(
    "/message/friends/set-remark",
    dependencies=[Depends(require_account_type(AccountType.ADMIN))],
    response_model=ApiResponse[None],
)
@portal_router.post(
    "/message/friends/set-remark",
    dependencies=[Depends(require_account_type(AccountType.PORTAL))],
    response_model=ApiResponse[None],
)
async def set_remark(
    payload: SetRemarkRequest,
    session: Annotated[SessionPayload, Depends(get_current_session)],
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[None]:
    await MsgFriendService(db).set_remark(payload, session)
    return success()


@admin_router.get(
    "/message/friends/my-requests",
    dependencies=[Depends(require_account_type(AccountType.ADMIN))],
    response_model=ApiResponse[list[FriendRequestSchema]],
)
@portal_router.get(
    "/message/friends/my-requests",
    dependencies=[Depends(require_account_type(AccountType.PORTAL))],
    response_model=ApiResponse[list[FriendRequestSchema]],
)
async def my_requests(
    session: Annotated[SessionPayload, Depends(get_current_session)],
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[list[FriendRequestSchema]]:
    return success(await MsgFriendService(db).my_requests(session))


@admin_router.get(
    "/message/friends/my-request-count",
    dependencies=[Depends(require_account_type(AccountType.ADMIN))],
    response_model=ApiResponse[MyRequestCountSchema],
)
@portal_router.get(
    "/message/friends/my-request-count",
    dependencies=[Depends(require_account_type(AccountType.PORTAL))],
    response_model=ApiResponse[MyRequestCountSchema],
)
async def my_request_count(
    session: Annotated[SessionPayload, Depends(get_current_session)],
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[MyRequestCountSchema]:
    return success(await MsgFriendService(db).my_request_count(session))
