"""
Generated by HEI code generator.
Author: Charlie
Generated at: 2026-07-23 16:28:53
"""

from datetime import datetime
from typing import Any

from pydantic import Field

from app.core.response.pagination import PageQuery
from app.core.schema.base import ApiSchema


# ── MsgFriend (legacy codegen) ──────────────────────────────────────────────

class MsgFriendCreateRequest(ApiSchema):
    account_type: str
    account_id: str
    friend_account_type: str
    friend_account_id: str
    remark: str | None = None
    status: str
    friend_at: datetime


class MsgFriendUpdateRequest(MsgFriendCreateRequest):
    id: str = Field(min_length=1, max_length=64)


class MsgFriendAdminPageQuery(PageQuery):
    status: str | None = None


class MsgFriendSchema(ApiSchema):
    id: str
    account_type: str
    account_id: str
    friend_account_type: str
    friend_account_id: str
    remark: str | None = None
    status: str
    friend_at: datetime
    created_at: datetime
    created_by: str | None = None
    updated_at: datetime
    updated_by: str | None = None


# ── Friend Request ───────────────────────────────────────────────────────────

class FriendRequestSchema(ApiSchema):
    """好友申请记录（含申请人/接收人资料信息）"""
    id: str
    applicant_type: str
    applicant_id: str
    applicant_name: str | None = None
    applicant_avatar: str | None = None
    recipient_type: str
    recipient_id: str
    recipient_name: str | None = None
    recipient_avatar: str | None = None
    message: str | None = None
    status: str
    handled_at: datetime | None = None
    created_at: datetime
    created_by: str | None = None
    updated_at: datetime
    updated_by: str | None = None


class ApplyFriendRequest(ApiSchema):
    """发送好友申请"""
    applicant_type: str
    applicant_id: str
    recipient_type: str
    recipient_id: str
    message: str | None = None


class HandleFriendRequest(ApiSchema):
    """处理好友申请（接受或拒绝）"""
    request_id: str
    action: str = Field(pattern="^(ACCEPT|REJECT)$")


class SetRemarkRequest(ApiSchema):
    """设置好友备注"""
    friendship_id: str
    remark: str | None = None


class RemoveFriendRequest(ApiSchema):
    """删除好友"""
    friendship_id: str


class SearchUserSchema(ApiSchema):
    """用户搜索结果"""
    account_type: str
    account_id: str
    account: str | None = None
    name: str | None = None
    nickname: str | None = None
    avatar: str | None = None
    signature: str | None = None
    is_friend: bool = False
    has_pending_request: bool = False


class FriendSchema(ApiSchema):
    """好友信息（含资料）"""
    friendship_id: str
    account_type: str
    account_id: str
    friend_account_type: str
    friend_account_id: str
    name: str | None = None
    nickname: str | None = None
    avatar: str | None = None
    signature: str | None = None
    remark: str | None = None
    friend_at: datetime


class MyRequestCountSchema(ApiSchema):
    """待处理好友申请数量"""
    pending_count: int


class FriendSearchQuery(ApiSchema):
    keyword: str = Field(min_length=1)
