"""
Generated by HEI code generator.
Author: Charlie
Generated at: 2026-07-23 16:28:53
"""

from datetime import datetime, timezone

from sqlalchemy import or_, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config.enums import AccountType
from app.core.exceptions.business import BusinessError
from app.core.response.pagination import PageData, build_page
from app.core.schema.base import IdQuery, IdsRequest, to_schema, to_schema_list
from app.core.security.session import SessionPayload
from app.modules.user.admin.model import AdminUserProfile
from app.modules.user.admin.repository import AdminUserProfileRepository
from app.modules.user.portal.model import PortalUserProfile
from app.modules.user.portal.repository import PortalUserProfileRepository
from app.platform.db.transaction import transactional
from app.modules.message.conversation.schema import CreateDirectConversationRequest
from app.modules.message.conversation.service import MsgConversationService
from app.modules.message.friend.model import MsgFriend
from app.platform.storage.url import resolve_file_url
from app.modules.message.friend.repository import (
    MsgFriendRepository,
)
from app.modules.message.friend.schema import (
    ApplyFriendRequest,
    FriendRequestSchema,
    FriendSchema,
    FriendSearchQuery,
    HandleFriendRequest,
    MyRequestCountSchema,
    MsgFriendAdminPageQuery,
    MsgFriendCreateRequest,
    MsgFriendSchema,
    MsgFriendUpdateRequest,
    RemoveFriendRequest,
    SearchUserSchema,
    SetRemarkRequest,
)


def _pick_profile_repo(db: AsyncSession, account_type: str):
    """根据账户类型返回对应的 profile 仓库"""
    if account_type == AccountType.ADMIN.value:
        return AdminUserProfileRepository(db)
    if account_type == AccountType.PORTAL.value:
        return PortalUserProfileRepository(db)
    raise BusinessError(f"Unsupported account type: {account_type}")


def _pick_profile_model(account_type: str):
    """根据账户类型返回对应的 profile 模型"""
    if account_type == AccountType.ADMIN.value:
        return AdminUserProfile
    if account_type == AccountType.PORTAL.value:
        return PortalUserProfile
    raise BusinessError(f"Unsupported account type: {account_type}")


async def _get_profile(db: AsyncSession, account_type: str, account_id: str):
    """获取单个用户的资料"""
    repo = _pick_profile_repo(db, account_type)
    return await repo.get_by_account_id(account_id)


async def _get_profiles_batch(
    db: AsyncSession, account_type: str, account_ids: list[str]
) -> dict[str, object]:
    """批量获取同一类型用户的资料，返回 {account_id: profile} 映射"""
    if not account_ids:
        return {}
    repo = _pick_profile_repo(db, account_type)
    profiles = await repo.list_by_account_ids(list(dict.fromkeys(account_ids)))
    return {p.account_id: p for p in profiles}


async def _enrich_friend_schema(
    db: AsyncSession, friend: MsgFriend
) -> FriendSchema:
    """为好友记录填充对方的资料信息"""
    profile = await _get_profile(db, friend.friend_account_type, friend.friend_account_id)
    return FriendSchema(
        friendship_id=friend.id,
        account_type=friend.account_type,
        account_id=friend.account_id,
        friend_account_type=friend.friend_account_type,
        friend_account_id=friend.friend_account_id,
        name=getattr(profile, "name", None),
        nickname=getattr(profile, "nickname", None),
        avatar=resolve_file_url(getattr(profile, "avatar", None)),
        signature=getattr(profile, "signature", None),
        remark=friend.remark,
        friend_at=friend.friend_at,
    )


async def _build_friend_request_schema(
    db: AsyncSession, req
) -> FriendRequestSchema:
    """为好友申请记录填充双方资料"""
    applicant_profile = await _get_profile(db, req.applicant_type, req.applicant_id)
    recipient_profile = await _get_profile(db, req.recipient_type, req.recipient_id)
    return FriendRequestSchema(
        id=req.id,
        applicant_type=req.applicant_type,
        applicant_id=req.applicant_id,
        applicant_name=getattr(applicant_profile, "name", None),
        applicant_avatar=resolve_file_url(getattr(applicant_profile, "avatar", None)),
        recipient_type=req.recipient_type,
        recipient_id=req.recipient_id,
        recipient_name=getattr(recipient_profile, "name", None),
        recipient_avatar=resolve_file_url(getattr(recipient_profile, "avatar", None)),
        message=req.message,
        status=req.status,
        handled_at=req.handled_at,
        created_at=req.created_at,
        created_by=req.created_by,
        updated_at=req.updated_at,
        updated_by=req.updated_by,
    )


class MsgFriendService:
    def __init__(self, db: AsyncSession):
        self.db = db
        self.repo = MsgFriendRepository(db)

    # ── Legacy CRUD (codegen) ───────────────────────────────────────────────

    async def create(self, payload: MsgFriendCreateRequest) -> None:
        async with transactional(self.db):
            await self.repo.create(payload)

    async def update(self, payload: MsgFriendUpdateRequest) -> None:
        async with transactional(self.db):
            await self.repo.update(payload)

    async def delete(self, payload: IdsRequest) -> None:
        async with transactional(self.db):
            await self.repo.delete_many(payload.ids)

    async def detail(self, query: IdQuery) -> MsgFriendSchema:
        return to_schema(MsgFriendSchema, await self.repo.get_required(query.id))

    async def page_admin(self, query: MsgFriendAdminPageQuery) -> PageData[MsgFriendSchema]:
        items, total = await self.repo.page_admin(query)
        return build_page(query.pagination, total, to_schema_list(MsgFriendSchema, items))

    # ── Apply friend request ────────────────────────────────────────────────

    async def apply(self, payload: ApplyFriendRequest, session: SessionPayload) -> None:
        """发送好友申请（已好友 / 已有待处理申请时幂等成功）"""
        # 不能加自己
        if (
            payload.applicant_type == payload.recipient_type
            and payload.applicant_id == payload.recipient_id
        ):
            raise BusinessError("Cannot send friend request to yourself")

        # 申请人必须与当前登录用户一致，防止伪造 applicant 身份
        if (
            payload.applicant_type != str(session.account_type)
            or payload.applicant_id != session.account_id
        ):
            raise BusinessError("Applicant must be the current user")

        created_or_reactivated = False
        request_id: str | None = None

        async with transactional(self.db):
            # 检查是否已经是好友
            existing = await self.repo.find_friendship(
                payload.applicant_type,
                payload.applicant_id,
                payload.recipient_type,
                payload.recipient_id,
            )
            if existing is not None:
                return

            # 检查是否有已存在的好友申请（任意状态）
            existing_req = await self.repo.find_any_request(
                payload.applicant_type,
                payload.applicant_id,
                payload.recipient_type,
                payload.recipient_id,
            )
            if existing_req is not None:
                if existing_req.status == "PENDING":
                    return
                # ACCEPTED 但上面已确认非好友（已删好友）→ 允许重新申请
                # REJECTED → 允许重新申请
                existing_req.status = "PENDING"
                existing_req.message = payload.message
                existing_req.handled_at = None
                existing_req.updated_at = datetime.now(timezone.utc)
                created_or_reactivated = True
                request_id = existing_req.id
            else:
                entity = await self.repo.create_friend_request(
                    {
                        "applicant_type": payload.applicant_type,
                        "applicant_id": payload.applicant_id,
                        "recipient_type": payload.recipient_type,
                        "recipient_id": payload.recipient_id,
                        "message": payload.message,
                        "status": "PENDING",
                    }
                )
                created_or_reactivated = True
                request_id = entity.id

        if created_or_reactivated and request_id:
            await self._push_friend_request_created(
                request_id=request_id,
                applicant_type=payload.applicant_type,
                applicant_id=payload.applicant_id,
                recipient_type=payload.recipient_type,
                recipient_id=payload.recipient_id,
                message=payload.message,
            )

    # ── Handle friend request ───────────────────────────────────────────────

    async def handle_request(
        self, payload: HandleFriendRequest, session: SessionPayload
    ) -> None:
        """处理好友申请：接受或拒绝。

        私聊会话必须在好友事务提交后再创建：create_direct 内部也有
        transactional，若嵌套在同一事务中失败会 rollback 整单，
        导致接口成功但申请仍停留在 PENDING。
        """
        peer_type: str | None = None
        peer_id: str | None = None

        async with transactional(self.db):
            req = await self.repo.get_friend_request_required(payload.request_id)

            if req.status != "PENDING":
                raise BusinessError("This request has already been handled")

            # 只有接收人才能处理（统一转 str，避免枚举/字符串比较偏差）
            if (
                str(req.recipient_type) != str(session.account_type)
                or str(req.recipient_id) != str(session.account_id)
            ):
                raise BusinessError("Only the recipient can handle this request")

            if payload.action == "ACCEPT":
                _accept_friend_request(self.repo, req, payload.request_id)
                peer_type = req.applicant_type
                peer_id = req.applicant_id
            elif payload.action == "REJECT":
                req.status = "REJECTED"
                req.handled_at = datetime.now(timezone.utc)

        if payload.action == "ACCEPT" and peer_type and peer_id:
            try:
                await MsgConversationService(self.db).create_direct(
                    CreateDirectConversationRequest(
                        account_type=peer_type,
                        account_id=peer_id,
                    ),
                    session,
                )
            except Exception:
                # 好友关系已落库；会话可稍后由用户手动打开时再创建
                pass

    # ── Remove friend ───────────────────────────────────────────────────────

    async def remove(self, payload: RemoveFriendRequest, session: SessionPayload) -> None:
        """删除好友：双向软删除 + 移除双方对话成员"""
        async with transactional(self.db):
            friendship = await self.repo.get_required(payload.friendship_id)
            await self.repo.delete_bidirectional(
                friendship.account_type,
                friendship.account_id,
                friendship.friend_account_type,
                friendship.friend_account_id,
            )

            # 移除双方在 DIRECT 对话中的成员身份
            from app.modules.message.conversation.repository import MsgConversationRepository
            conv_repo = MsgConversationRepository(self.db)
            direct_conv = await conv_repo.find_direct_conversation(
                friendship.account_type, friendship.account_id,
                friendship.friend_account_type, friendship.friend_account_id,
            )
            if direct_conv:
                await conv_repo.remove_member(
                    direct_conv.id, friendship.account_type, friendship.account_id,
                )
                await conv_repo.remove_member(
                    direct_conv.id, friendship.friend_account_type, friendship.friend_account_id,
                )

    # ── My friends ──────────────────────────────────────────────────────────

    async def my_list(self, session: SessionPayload) -> list[FriendSchema]:
        """我的好友列表（含对方资料，批量加载 profile 避免 N+1）"""
        friends = await self.repo.list_my_friends(
            session.account_type, session.account_id
        )
        if not friends:
            return []

        admin_ids = []
        portal_ids = []
        for f in friends:
            (admin_ids if f.friend_account_type == "ADMIN" else portal_ids).append(f.friend_account_id)
        admin_profiles = await _get_profiles_batch(self.db, "ADMIN", admin_ids) if admin_ids else {}
        portal_profiles = await _get_profiles_batch(self.db, "PORTAL", portal_ids) if portal_ids else {}

        result: list[FriendSchema] = []
        for f in friends:
            profiles = admin_profiles if f.friend_account_type == "ADMIN" else portal_profiles
            profile = profiles.get(f.friend_account_id)
            result.append(FriendSchema(
                friendship_id=f.id,
                account_type=f.account_type,
                account_id=f.account_id,
                friend_account_type=f.friend_account_type,
                friend_account_id=f.friend_account_id,
                name=getattr(profile, "name", None),
                nickname=getattr(profile, "nickname", None),
                avatar=resolve_file_url(getattr(profile, "avatar", None)),
                signature=getattr(profile, "signature", None),
                remark=f.remark,
                friend_at=f.friend_at,
            ))
        return result

    # ── Search users ────────────────────────────────────────────────────────

    async def search(
        self, query: FriendSearchQuery, session: SessionPayload
    ) -> list[SearchUserSchema]:
        """搜索用户（非自己、非好友），通过 profile 的 name/nickname 和登录用户名匹配"""
        from app.modules.iam.account.model import SysAccount, SysAccountIdentity
        from app.modules.iam.enums import AccountIdentityType

        keyword = query.keyword
        keyword_like = f"%{keyword}%"
        results: list[SearchUserSchema] = []
        seen: set[tuple[str, str]] = set()

        # 获取我的好友 / 待处理申请，用于标记状态（仍排除自己）
        my_friends = await self.repo.list_my_friends(
            session.account_type, session.account_id
        )
        friend_ids = {(f.friend_account_type, f.friend_account_id) for f in my_friends}
        pending_out = await self.repo.find_friend_requests_by_applicant(
            session.account_type, session.account_id
        )
        pending_ids = {
            (r.recipient_type, r.recipient_id)
            for r in pending_out
            if r.status == "PENDING"
        }
        self_key = (session.account_type, session.account_id)

        for account_type in (AccountType.ADMIN.value, AccountType.PORTAL.value):
            profile_model = _pick_profile_model(account_type)

            # -- profile name/nickname 匹配 --
            stmt = (
                select(profile_model)
                .where(
                    or_(
                        profile_model.name.ilike(keyword_like),
                        profile_model.nickname.ilike(keyword_like),
                    )
                )
                .limit(50)
            )
            for p in (await self.db.execute(stmt)).scalars().all():
                key = (account_type, p.account_id)
                if key == self_key or key in seen:
                    continue
                seen.add(key)
                results.append(
                    SearchUserSchema(
                        account_type=account_type,
                        account_id=p.account_id,
                        name=getattr(p, "name", None),
                        nickname=getattr(p, "nickname", None),
                        avatar=resolve_file_url(getattr(p, "avatar", None)),
                        signature=getattr(p, "signature", None),
                        is_friend=key in friend_ids,
                        has_pending_request=key in pending_ids,
                    )
                )

            # -- 用户名（SysAccountIdentity.identifier）匹配 --
            id_stmt = (
                select(SysAccountIdentity.account_id, SysAccountIdentity.identifier)
                .join(SysAccount, SysAccountIdentity.account_id == SysAccount.id)
                .where(
                    SysAccountIdentity.identity_type == AccountIdentityType.ACCOUNT.value,
                    SysAccount.account_type == account_type,
                    SysAccountIdentity.identifier.ilike(keyword_like),
                )
                .limit(50)
            )
            for row in (await self.db.execute(id_stmt)).all():
                acct_id, username = row
                key = (account_type, acct_id)
                if key == self_key or key in seen:
                    continue
                seen.add(key)
                profile = await self.db.get(profile_model, acct_id)
                results.append(
                    SearchUserSchema(
                        account_type=account_type,
                        account_id=acct_id,
                        account=username,
                        name=getattr(profile, "name", None) if profile else None,
                        nickname=getattr(profile, "nickname", None) if profile else None,
                        avatar=resolve_file_url(getattr(profile, "avatar", None)) if profile else None,
                        signature=getattr(profile, "signature", None) if profile else None,
                        is_friend=key in friend_ids,
                        has_pending_request=key in pending_ids,
                    )
                )

        # 为 profile-matched 结果批量填充 account 字段
        ids_needing_account = [r.account_id for r in results if r.account is None]
        if ids_needing_account:
            acct_stmt = (
                select(SysAccountIdentity.account_id, SysAccountIdentity.identifier)
                .where(
                    SysAccountIdentity.account_id.in_(list(dict.fromkeys(ids_needing_account))),
                    SysAccountIdentity.identity_type == AccountIdentityType.ACCOUNT.value,
                )
            )
            acct_map = {row[0]: row[1] for row in (await self.db.execute(acct_stmt)).all()}
            for r in results:
                if r.account is None:
                    r.account = acct_map.get(r.account_id)

        return results

    # ── Set remark ──────────────────────────────────────────────────────────

    async def set_remark(
        self, payload: SetRemarkRequest, session: SessionPayload
    ) -> None:
        """设置好友备注"""
        async with transactional(self.db):
            await self.repo.update_remark(payload.friendship_id, payload.remark)

    # ── My requests ─────────────────────────────────────────────────────────

    async def my_requests(
        self, session: SessionPayload
    ) -> list[FriendRequestSchema]:
        """我的好友申请（发出的 + 收到的），批量加载 profile 避免 N+1"""
        requests = await self.repo.find_all_requests_for_user(
            session.account_type, session.account_id
        )
        if not requests:
            return []

        applicant_admin_ids = []
        applicant_portal_ids = []
        recipient_admin_ids = []
        recipient_portal_ids = []
        for req in requests:
            (applicant_admin_ids if req.applicant_type == "ADMIN" else applicant_portal_ids).append(req.applicant_id)
            (recipient_admin_ids if req.recipient_type == "ADMIN" else recipient_portal_ids).append(req.recipient_id)

        admin_apps = await _get_profiles_batch(self.db, "ADMIN", applicant_admin_ids) if applicant_admin_ids else {}
        portal_apps = await _get_profiles_batch(self.db, "PORTAL", applicant_portal_ids) if applicant_portal_ids else {}
        admin_recips = await _get_profiles_batch(self.db, "ADMIN", recipient_admin_ids) if recipient_admin_ids else {}
        portal_recips = await _get_profiles_batch(self.db, "PORTAL", recipient_portal_ids) if recipient_portal_ids else {}

        result: list[FriendRequestSchema] = []
        for req in requests:
            apps = admin_apps if req.applicant_type == "ADMIN" else portal_apps
            recips = admin_recips if req.recipient_type == "ADMIN" else portal_recips

            app_profile = apps.get(req.applicant_id)
            recip_profile = recips.get(req.recipient_id)

            result.append(FriendRequestSchema(
                id=req.id,
                applicant_type=req.applicant_type,
                applicant_id=req.applicant_id,
                applicant_name=getattr(app_profile, "name", None),
                applicant_avatar=resolve_file_url(getattr(app_profile, "avatar", None)),
                recipient_type=req.recipient_type,
                recipient_id=req.recipient_id,
                recipient_name=getattr(recip_profile, "name", None),
                recipient_avatar=resolve_file_url(getattr(recip_profile, "avatar", None)),
                message=req.message,
                status=req.status,
                handled_at=req.handled_at,
                created_at=req.created_at,
                created_by=req.created_by,
                updated_at=req.updated_at,
                updated_by=req.updated_by,
            ))
        return result

    # ── My request count ────────────────────────────────────────────────────

    async def my_request_count(
        self, session: SessionPayload
    ) -> MyRequestCountSchema:
        """我收到的待处理好友申请数量"""
        count = await self.repo.count_pending_requests(
            session.account_type, session.account_id
        )
        return MyRequestCountSchema(pending_count=count)

    async def _push_friend_request_created(
        self,
        *,
        request_id: str,
        applicant_type: str,
        applicant_id: str,
        recipient_type: str,
        recipient_id: str,
        message: str | None,
    ) -> None:
        """推送新好友申请给接收方（铃铛 / 申请列表实时刷新）"""
        try:
            from app.modules.message.websocket.handler import manager as ws_manager

            profile = await _get_profile(self.db, applicant_type, applicant_id)
            ws_payload = {
                "type": "new_friend_request",
                "data": {
                    "id": request_id,
                    "applicant_type": applicant_type,
                    "applicant_id": applicant_id,
                    "applicant_name": getattr(profile, "name", None) if profile else None,
                    "applicant_avatar": resolve_file_url(
                        getattr(profile, "avatar", None)
                    )
                    if profile
                    else None,
                    "recipient_type": recipient_type,
                    "recipient_id": recipient_id,
                    "message": message,
                    "status": "PENDING",
                },
            }
            await ws_manager.route_to_user(recipient_type, recipient_id, ws_payload)
        except Exception:
            pass


def _accept_friend_request(
    repo: MsgFriendRepository, req, request_id: str
) -> None:
    """在同一个事务中：标记请求为已接受 + 创建双向好友记录"""
    now = datetime.now(timezone.utc)

    req.status = "ACCEPTED"
    req.handled_at = now

    # 创建双向好友记录
    friend1 = MsgFriend(
        account_type=req.applicant_type,
        account_id=req.applicant_id,
        friend_account_type=req.recipient_type,
        friend_account_id=req.recipient_id,
        remark=req.message[:64] if req.message else None,
        status="ACTIVE",
        friend_at=now,
    )
    friend2 = MsgFriend(
        account_type=req.recipient_type,
        account_id=req.recipient_id,
        friend_account_type=req.applicant_type,
        friend_account_id=req.applicant_id,
        status="ACTIVE",
        friend_at=now,
    )
    repo.db.add(friend1)
    repo.db.add(friend2)
