"""
Generated by HEI code generator.
Author: Charlie
Generated at: 2026-07-23 16:28:50
"""

from typing import Annotated

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config.enums import AccountType
from app.core.response.pagination import PageData
from app.core.response.schema import ApiResponse, success
from app.core.schema.base import IdQuery, IdsRequest
from app.core.security.session import SessionPayload
from app.deps.auth import get_current_session, require_account_type, require_permission
from app.deps.db import get_db_session
from app.modules.message.notification.schema import (
    MsgNotificationAdminPageQuery,
    MsgNotificationCreateRequest,
    MsgNotificationSchema,
    MsgNotificationUpdateRequest,
    MyNotificationPageQuery,
    NotificationReadRequest,
)
from app.modules.message.notification.service import (
    MsgNotificationService,
)

admin_router = APIRouter()
portal_router = APIRouter()


# ── Admin routes ──────────────────────────────────────────────────────────────


@admin_router.post(
    "/message/notifications/create",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("message:notification:create")),
    ],
    response_model=ApiResponse[None],
)
async def create(
    payload: MsgNotificationCreateRequest,
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[None]:
    await MsgNotificationService(db).create(payload)
    return success()


@admin_router.post(
    "/message/notifications/update",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("message:notification:update")),
    ],
    response_model=ApiResponse[None],
)
async def update(
    payload: MsgNotificationUpdateRequest,
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[None]:
    await MsgNotificationService(db).update(payload)
    return success()


@admin_router.post(
    "/message/notifications/delete",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("message:notification:delete")),
    ],
    response_model=ApiResponse[None],
)
async def delete(
    payload: IdsRequest,
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[None]:
    await MsgNotificationService(db).delete(payload)
    return success()


@admin_router.get(
    "/message/notifications/detail",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("message:notification:detail")),
    ],
    response_model=ApiResponse[MsgNotificationSchema],
)
async def detail(
    query: Annotated[IdQuery, Depends()],
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[MsgNotificationSchema]:
    return success(await MsgNotificationService(db).detail(query))


@admin_router.get(
    "/message/notifications/page",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("message:notification:page")),
    ],
    response_model=ApiResponse[PageData[MsgNotificationSchema]],
)
async def page(
    query: Annotated[MsgNotificationAdminPageQuery, Depends()],
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[PageData[MsgNotificationSchema]]:
    return success(await MsgNotificationService(db).page_admin(query))


@admin_router.post(
    "/message/notifications/publish",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("message:notification:publish")),
    ],
    response_model=ApiResponse[None],
)
async def publish(
    payload: IdsRequest,
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[None]:
    await MsgNotificationService(db).publish(payload)
    return success()


@admin_router.post(
    "/message/notifications/revoke",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("message:notification:revoke")),
    ],
    response_model=ApiResponse[None],
)
async def revoke(
    payload: IdsRequest,
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[None]:
    await MsgNotificationService(db).revoke(payload)
    return success()


# ── Portal / current-user routes ──────────────────────────────────────────────


def register_current_user_routes(router: APIRouter) -> None:
    """Register notification routes for the currently logged-in user."""

    @router.get(
        "/message/notifications/my-page",
        response_model=ApiResponse[PageData[MsgNotificationSchema]],
    )
    async def my_page(
        query: Annotated[MyNotificationPageQuery, Depends()],
        db: Annotated[AsyncSession, Depends(get_db_session)],
        session: Annotated[SessionPayload, Depends(get_current_session)],
    ) -> ApiResponse[PageData[MsgNotificationSchema]]:
        return success(await MsgNotificationService(db).page_my_notifications(query, session))

    @router.get(
        "/message/notifications/my-detail",
        response_model=ApiResponse[MsgNotificationSchema],
    )
    async def my_detail(
        query: Annotated[IdQuery, Depends()],
        db: Annotated[AsyncSession, Depends(get_db_session)],
        session: Annotated[SessionPayload, Depends(get_current_session)],
    ) -> ApiResponse[MsgNotificationSchema]:
        return success(await MsgNotificationService(db).my_detail(query, session))

    @router.get(
        "/message/notifications/unread-count",
        response_model=ApiResponse[int],
    )
    async def unread_count(
        db: Annotated[AsyncSession, Depends(get_db_session)],
        session: Annotated[SessionPayload, Depends(get_current_session)],
    ) -> ApiResponse[int]:
        return success(await MsgNotificationService(db).count_unread(session))

    @router.post(
        "/message/notifications/read",
        response_model=ApiResponse[None],
    )
    async def read(
        payload: NotificationReadRequest,
        db: Annotated[AsyncSession, Depends(get_db_session)],
        session: Annotated[SessionPayload, Depends(get_current_session)],
    ) -> ApiResponse[None]:
        await MsgNotificationService(db).mark_read(payload, session)
        return success()

    @router.post(
        "/message/notifications/read-all",
        response_model=ApiResponse[None],
    )
    async def read_all(
        db: Annotated[AsyncSession, Depends(get_db_session)],
        session: Annotated[SessionPayload, Depends(get_current_session)],
    ) -> ApiResponse[None]:
        await MsgNotificationService(db).mark_all_read(session)
        return success()


register_current_user_routes(portal_router)
register_current_user_routes(admin_router)
