"""
Generated by HEI code generator.
Author: Charlie
Generated at: 2026-07-23 16:28:50
"""

from datetime import datetime
from typing import Any

from pydantic import Field

from app.core.response.pagination import PageQuery
from app.core.schema.base import ApiSchema, Id


class MsgNotificationCreateRequest(ApiSchema):
    title: str
    content: str
    content_type: str
    category: str
    severity: str
    target_scope: str
    target_account_types: list[str] = Field(default_factory=list)
    target_account_ids: list[str] = Field(default_factory=list)
    target_dept_ids: list[str] = Field(default_factory=list)
    target_role_ids: list[str] = Field(default_factory=list)
    sender_account_type: str | None = None
    sender_account_id: str | None = None
    source_type: str | None = None
    source_id: str | None = None
    status: str
    publish_at: datetime | None = None
    revoked_at: datetime | None = None
    extra: dict[str, Any]


class MsgNotificationUpdateRequest(MsgNotificationCreateRequest):
    id: str = Field(min_length=1, max_length=64)


class MsgNotificationAdminPageQuery(PageQuery):
    title: str | None = None
    category: str | None = None
    status: str | None = None


class MsgNotificationSchema(ApiSchema):
    id: str
    title: str
    content: str
    content_type: str
    category: str
    severity: str
    target_scope: str
    target_account_types: list[str] = Field(default_factory=list)
    target_account_ids: list[str] = Field(default_factory=list)
    target_dept_ids: list[str] = Field(default_factory=list)
    target_role_ids: list[str] = Field(default_factory=list)
    sender_account_type: str | None = None
    sender_account_id: str | None = None
    source_type: str | None = None
    source_id: str | None = None
    status: str
    publish_at: datetime | None = None
    revoked_at: datetime | None = None
    extra: dict[str, Any]
    created_at: datetime
    created_by: str | None = None
    updated_at: datetime
    updated_by: str | None = None
    created_name: str | None = None
    updated_name: str | None = None
    is_read: bool = False


class NotificationReadRequest(ApiSchema):
    ids: list[Id] = Field(min_length=1)


class MyNotificationPageQuery(PageQuery):
    category: str | None = None
