"""
Generated by HEI code generator.
Author: Charlie
Generated at: 2026-07-23 16:28:50
"""

from datetime import datetime

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config.enums import AccountType
from app.core.response.pagination import PageData, build_page
from app.core.schema.base import IdQuery, IdsRequest, to_schema, to_schema_list
from app.modules.message.enums import NotificationStatus
from app.modules.message.notification.model import MsgNotificationRead
from app.modules.user.utils.profile import get_profiles_batch
from app.platform.db.transaction import transactional
from app.modules.message.notification.repository import (
    MsgNotificationRepository,
)
from app.modules.message.notification.schema import (
    MsgNotificationAdminPageQuery,
    MsgNotificationCreateRequest,
    MsgNotificationSchema,
    MsgNotificationUpdateRequest,
    MyNotificationPageQuery,
    NotificationReadRequest,
)


class MsgNotificationService:
    def __init__(self, db: AsyncSession):
        self.db = db
        self.repo = MsgNotificationRepository(db)

    async def create(self, payload: MsgNotificationCreateRequest) -> None:
        async with transactional(self.db):
            await self.repo.create(payload)

    async def update(self, payload: MsgNotificationUpdateRequest) -> None:
        async with transactional(self.db):
            await self.repo.update(payload)

    async def delete(self, payload: IdsRequest) -> None:
        async with transactional(self.db):
            await self.repo.delete_many(payload.ids)

    async def detail(self, query: IdQuery) -> MsgNotificationSchema:
        entity = await self.repo.get_required(query.id)
        schema = to_schema(MsgNotificationSchema, entity)
        return await self._enrich_profiles(schema)

    async def page_admin(self, query: MsgNotificationAdminPageQuery) -> PageData[MsgNotificationSchema]:
        items, total = await self.repo.page_admin(query)
        schemas = to_schema_list(MsgNotificationSchema, items)
        return build_page(query.pagination, total, await self._batch_enrich_profiles(schemas))

    async def publish(self, payload: IdsRequest) -> None:
        """Set status=PUBLISHED and publish_at=now (only from DRAFT)."""
        published = []
        async with transactional(self.db):
            for nid in payload.ids:
                notification = await self.repo.get_required(nid)
                if notification.status != NotificationStatus.DRAFT:
                    continue
                notification.status = NotificationStatus.PUBLISHED
                notification.publish_at = datetime.utcnow()
                self.db.add(notification)
                published.append(notification)
            await self.db.flush()

        # Push via WebSocket to target users
        try:
            from app.modules.message.websocket.handler import manager as ws_manager
            for notification in published:
                if notification.target_scope == "SPECIFIC" and notification.target_account_ids:
                    schema = to_schema(MsgNotificationSchema, notification)
                    ws_payload = {
                        "type": "new_notification",
                        "data": schema.model_dump(mode="json"),
                    }
                    acct_types = notification.target_account_types or []
                    for i, acct_id in enumerate(notification.target_account_ids):
                        acct_type = acct_types[i] if i < len(acct_types) else None
                        if acct_type:
                            await ws_manager.route_to_user(acct_type, acct_id, ws_payload)
        except Exception:
            pass

    async def revoke(self, payload: IdsRequest) -> None:
        """Set status=REVOKED and revoked_at=now (only from PUBLISHED)."""
        async with transactional(self.db):
            for nid in payload.ids:
                notification = await self.repo.get_required(nid)
                if notification.status != NotificationStatus.PUBLISHED:
                    continue
                notification.status = NotificationStatus.REVOKED
                notification.revoked_at = datetime.utcnow()
                self.db.add(notification)
            await self.db.flush()

    async def page_my_notifications(self, query: MyNotificationPageQuery, session) -> PageData[MsgNotificationSchema]:
        account_type = session.account_type
        account_id = session.account_id
        items, total, read_id_set = await self.repo.page_my_notifications(query, account_type, account_id)
        schemas = to_schema_list(MsgNotificationSchema, items)
        for schema_item in schemas:
            schema_item.is_read = schema_item.id in read_id_set
        return build_page(query.pagination, total, schemas)

    async def my_detail(self, query: IdQuery, session) -> MsgNotificationSchema:
        account_type = session.account_type
        account_id = session.account_id
        notification = await self.repo.get_required(query.id)
        schema_item = to_schema(MsgNotificationSchema, notification)
        stmt = select(MsgNotificationRead.notification_id).where(
            MsgNotificationRead.notification_id == query.id,
            MsgNotificationRead.account_type == account_type,
            MsgNotificationRead.account_id == account_id,
        )
        result = (await self.db.execute(stmt)).scalars().first()
        schema_item.is_read = result is not None
        return schema_item

    async def count_unread(self, session) -> int:
        return await self.repo.count_unread(session.account_type, session.account_id)

    async def mark_read(self, payload: NotificationReadRequest, session) -> None:
        async with transactional(self.db):
            await self.repo.mark_read(payload.ids, session.account_type, session.account_id)

    async def mark_all_read(self, session) -> None:
        async with transactional(self.db):
            await self.repo.mark_all_read(session.account_type, session.account_id)

    async def _enrich_profiles(self, schema: MsgNotificationSchema) -> MsgNotificationSchema:
        ids = []
        if schema.created_by:
            ids.append(schema.created_by)
        if schema.updated_by:
            ids.append(schema.updated_by)
        if not ids:
            return schema
        profiles = await get_profiles_batch(self.db, AccountType.ADMIN, ids)
        if schema.created_by and schema.created_by in profiles:
            schema.created_name = profiles[schema.created_by].name
        if schema.updated_by and schema.updated_by in profiles:
            schema.updated_name = profiles[schema.updated_by].name
        return schema

    async def _batch_enrich_profiles(self, schemas: list[MsgNotificationSchema]) -> list[MsgNotificationSchema]:
        all_ids = set()
        for schema in schemas:
            if schema.created_by:
                all_ids.add(schema.created_by)
            if schema.updated_by:
                all_ids.add(schema.updated_by)
        if not all_ids:
            return schemas
        profiles = await get_profiles_batch(self.db, AccountType.ADMIN, list(all_ids))
        for schema in schemas:
            if schema.created_by and schema.created_by in profiles:
                schema.created_name = profiles[schema.created_by].name
            if schema.updated_by and schema.updated_by in profiles:
                schema.updated_name = profiles[schema.updated_by].name
        return schemas
