"""
Generated by HEI code generator.
Author: Charlie
Generated at: 2026-07-23 16:28:51
"""

from datetime import datetime, timezone

from sqlalchemy import Select, String, cast, delete, func, or_, select, update
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.exceptions.business import NotFoundError
from app.modules.message.announcement.model import (
    MsgAnnouncement,
    MsgAnnouncementRead,
)
from app.modules.message.announcement.schema import (
    MsgAnnouncementAdminPageQuery,
    MsgAnnouncementCreateRequest,
    MsgAnnouncementUpdateRequest,
    MyAnnouncementPageQuery,
)
from app.modules.message.enums import AnnouncementStatus, TargetScope


class MsgAnnouncementRepository:
    def __init__(self, db: AsyncSession):
        self.db = db

    async def create(self, payload: MsgAnnouncementCreateRequest) -> MsgAnnouncement:
        entity = MsgAnnouncement(**payload.model_dump())
        self.db.add(entity)
        await self.db.flush()
        return entity

    async def get_by_id(self, entity_id: str) -> MsgAnnouncement | None:
        return await self.db.get(MsgAnnouncement, entity_id)

    async def get_required(self, entity_id: str) -> MsgAnnouncement:
        entity = await self.get_by_id(entity_id)
        if entity is None:
            raise NotFoundError("MsgAnnouncement not found")
        return entity

    async def update(self, payload: MsgAnnouncementUpdateRequest) -> None:
        entity = await self.get_required(payload.id)
        for key, value in payload.model_dump(exclude={"id"}).items():
            setattr(entity, key, value)
        await self.db.flush()

    async def delete_many(self, entity_ids: list[str]) -> None:
        unique_ids = list(dict.fromkeys(entity_ids))
        stmt = select(MsgAnnouncement.id).where(MsgAnnouncement.id.in_(unique_ids))
        existing_ids = set((await self.db.execute(stmt)).scalars().all())
        if len(existing_ids) != len(unique_ids):
            raise NotFoundError("MsgAnnouncement not found")
        await self.db.execute(delete(MsgAnnouncement).where(MsgAnnouncement.id.in_(unique_ids)))

    async def page_admin(self, query: MsgAnnouncementAdminPageQuery) -> tuple[list[MsgAnnouncement], int]:
        stmt: Select[tuple[MsgAnnouncement]] = select(MsgAnnouncement)
        count_stmt = select(func.count(MsgAnnouncement.id))
        filters = []
        if query.title:
            filters.append(MsgAnnouncement.title.ilike(f"%{query.title}%"))
        if query.status is not None:
            filters.append(MsgAnnouncement.status == query.status)
        if filters:
            stmt = stmt.where(*filters)
            count_stmt = count_stmt.where(*filters)
        stmt = stmt.order_by(MsgAnnouncement.id.desc()).offset(query.pagination.offset).limit(query.pagination.size)
        items = list((await self.db.execute(stmt)).scalars().all())
        total = (await self.db.execute(count_stmt)).scalar_one()
        return items, total

    async def page_my_announcements(
        self,
        query: MyAnnouncementPageQuery,
        account_type: str,
        account_id: str | None = None,
    ) -> tuple[list[MsgAnnouncement], int, set[str]]:
        now = datetime.now(timezone.utc)
        stmt: Select[tuple[MsgAnnouncement]] = select(MsgAnnouncement).where(
            MsgAnnouncement.status == AnnouncementStatus.PUBLISHED.value,
            or_(
                MsgAnnouncement.expire_at.is_(None),
                MsgAnnouncement.expire_at > now,
            ),
            or_(
                MsgAnnouncement.target_scope == TargetScope.ALL.value,
                (func.json_array_length(MsgAnnouncement.target_account_types) == 0)
                | cast(MsgAnnouncement.target_account_types, String).contains('"' + account_type + '"'),
            ),
        )
        count_stmt = select(func.count(MsgAnnouncement.id)).where(
            MsgAnnouncement.status == AnnouncementStatus.PUBLISHED.value,
            or_(
                MsgAnnouncement.expire_at.is_(None),
                MsgAnnouncement.expire_at > now,
            ),
            or_(
                MsgAnnouncement.target_scope == TargetScope.ALL.value,
                (func.json_array_length(MsgAnnouncement.target_account_types) == 0)
                | cast(MsgAnnouncement.target_account_types, String).contains('"' + account_type + '"'),
            ),
        )
        stmt = stmt.order_by(
            MsgAnnouncement.is_pinned.desc(),
            MsgAnnouncement.publish_at.desc(),
        ).offset(query.pagination.offset).limit(query.pagination.size)
        items = list((await self.db.execute(stmt)).scalars().all())
        total = (await self.db.execute(count_stmt)).scalar_one()

        read_id_set: set[str] = set()
        if items and account_id:
            announcement_ids = [item.id for item in items]
            read_stmt = select(MsgAnnouncementRead.announcement_id).where(
                MsgAnnouncementRead.announcement_id.in_(announcement_ids),
                MsgAnnouncementRead.account_type == account_type,
                MsgAnnouncementRead.account_id == account_id,
            )
            read_ids = list((await self.db.execute(read_stmt)).scalars().all())
            read_id_set = set(read_ids)

        return items, total, read_id_set

    async def count_unread(self, account_type: str, account_id: str) -> int:
        now = datetime.now(timezone.utc)
        published_stmt = select(MsgAnnouncement.id).where(
            MsgAnnouncement.status == AnnouncementStatus.PUBLISHED.value,
            or_(
                MsgAnnouncement.expire_at.is_(None),
                MsgAnnouncement.expire_at > now,
            ),
            or_(
                MsgAnnouncement.target_scope == TargetScope.ALL.value,
                (func.json_array_length(MsgAnnouncement.target_account_types) == 0)
                | cast(MsgAnnouncement.target_account_types, String).contains('"' + account_type + '"'),
            ),
        )
        published_ids = {str(v) for v in (await self.db.execute(published_stmt)).scalars().all()}
        if not published_ids:
            return 0

        read_stmt = select(MsgAnnouncementRead.announcement_id).where(
            MsgAnnouncementRead.account_type == account_type,
            MsgAnnouncementRead.account_id == account_id,
            MsgAnnouncementRead.announcement_id.in_(list(published_ids)),
        )
        read_ids = set((await self.db.execute(read_stmt)).scalars().all())
        return len(published_ids - read_ids)

    async def mark_read(self, ids: list[str], account_type: str, account_id: str) -> None:
        unique_ids = list(dict.fromkeys(ids))
        existing_stmt = select(MsgAnnouncementRead.announcement_id).where(
            MsgAnnouncementRead.announcement_id.in_(unique_ids),
            MsgAnnouncementRead.account_type == account_type,
            MsgAnnouncementRead.account_id == account_id,
        )
        existing_ids = set((await self.db.execute(existing_stmt)).scalars().all())
        new_ids = [aid for aid in unique_ids if aid not in existing_ids]
        for announcement_id in new_ids:
            self.db.add(
                MsgAnnouncementRead(
                    announcement_id=announcement_id,
                    account_type=account_type,
                    account_id=account_id,
                )
            )
        if new_ids:
            await self.db.flush()

    async def mark_all_read(self, account_type: str, account_id: str) -> None:
        now = datetime.now(timezone.utc)
        published_stmt = select(MsgAnnouncement.id).where(
            MsgAnnouncement.status == AnnouncementStatus.PUBLISHED.value,
            or_(
                MsgAnnouncement.expire_at.is_(None),
                MsgAnnouncement.expire_at > now,
            ),
            or_(
                MsgAnnouncement.target_scope == TargetScope.ALL.value,
                (func.json_array_length(MsgAnnouncement.target_account_types) == 0)
                | cast(MsgAnnouncement.target_account_types, String).contains('"' + account_type + '"'),
            ),
        )
        published_ids = [str(v) for v in (await self.db.execute(published_stmt)).scalars().all()]

        existing_stmt = select(MsgAnnouncementRead.announcement_id).where(
            MsgAnnouncementRead.announcement_id.in_(published_ids),
            MsgAnnouncementRead.account_type == account_type,
            MsgAnnouncementRead.account_id == account_id,
        )
        existing_ids = set((await self.db.execute(existing_stmt)).scalars().all())
        new_ids = [aid for aid in published_ids if aid not in existing_ids]
        for announcement_id in new_ids:
            self.db.add(
                MsgAnnouncementRead(
                    announcement_id=announcement_id,
                    account_type=account_type,
                    account_id=account_id,
                )
            )
        if new_ids:
            await self.db.flush()

    async def increment_view_count(self, entity_id: str) -> None:
        await self.db.execute(
            update(MsgAnnouncement)
            .where(MsgAnnouncement.id == entity_id)
            .values(view_count=MsgAnnouncement.view_count + 1)
        )
        await self.db.flush()
