"""
Generated by HEI code generator.
Author: Charlie
Generated at: 2026-07-23 16:28:51
"""

from typing import Annotated

from fastapi import APIRouter, Depends
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config.enums import AccountType
from app.core.response.pagination import PageData
from app.core.response.schema import ApiResponse, success
from app.core.schema.base import IdQuery, IdsRequest
from app.core.security.session import SessionPayload
from app.deps.auth import get_current_session, get_optional_session, require_account_type, require_permission
from app.deps.db import get_db_session
from app.modules.message.announcement.schema import (
    AnnouncementReadRequest,
    MsgAnnouncementAdminPageQuery,
    MsgAnnouncementCreateRequest,
    MsgAnnouncementSchema,
    MsgAnnouncementUpdateRequest,
    MyAnnouncementPageQuery,
    PinAnnouncementRequest,
)
from app.modules.message.announcement.service import (
    MsgAnnouncementService,
)

admin_router = APIRouter()
portal_router = APIRouter()


@portal_router.get(
    "/message/announcements/list",
    response_model=ApiResponse[PageData[MsgAnnouncementSchema]],
)
async def portal_announcement_list(
    db: Annotated[AsyncSession, Depends(get_db_session)],
    query: Annotated[MyAnnouncementPageQuery, Depends()],
    session: Annotated[SessionPayload | None, Depends(get_optional_session)] = None,
) -> ApiResponse[PageData[MsgAnnouncementSchema]]:
    return success(await MsgAnnouncementService(db).page_portal_list(query, session))


# ==================== Admin CRUD ====================

@admin_router.post(
    "/message/announcements/create",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("message:announcement:create")),
    ],
    response_model=ApiResponse[None],
)
async def create(
    payload: MsgAnnouncementCreateRequest,
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[None]:
    await MsgAnnouncementService(db).create(payload)
    return success()


@admin_router.post(
    "/message/announcements/update",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("message:announcement:update")),
    ],
    response_model=ApiResponse[None],
)
async def update(
    payload: MsgAnnouncementUpdateRequest,
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[None]:
    await MsgAnnouncementService(db).update(payload)
    return success()


@admin_router.post(
    "/message/announcements/delete",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("message:announcement:delete")),
    ],
    response_model=ApiResponse[None],
)
async def delete(
    payload: IdsRequest,
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[None]:
    await MsgAnnouncementService(db).delete(payload)
    return success()


@admin_router.get(
    "/message/announcements/detail",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("message:announcement:detail")),
    ],
    response_model=ApiResponse[MsgAnnouncementSchema],
)
async def detail(
    query: Annotated[IdQuery, Depends()],
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[MsgAnnouncementSchema]:
    return success(await MsgAnnouncementService(db).detail(query))


@admin_router.get(
    "/message/announcements/page",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("message:announcement:page")),
    ],
    response_model=ApiResponse[PageData[MsgAnnouncementSchema]],
)
async def page(
    query: Annotated[MsgAnnouncementAdminPageQuery, Depends()],
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[PageData[MsgAnnouncementSchema]]:
    return success(await MsgAnnouncementService(db).page_admin(query))


# ==================== Admin Business Operations ====================

@admin_router.post(
    "/message/announcements/publish",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("message:announcement:publish")),
    ],
    response_model=ApiResponse[None],
)
async def publish(
    payload: IdsRequest,
    db: Annotated[AsyncSession, Depends(get_db_session)],
    session: Annotated[SessionPayload, Depends(get_current_session)],
) -> ApiResponse[None]:
    await MsgAnnouncementService(db).publish(payload, session)
    return success()


@admin_router.post(
    "/message/announcements/revoke",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("message:announcement:revoke")),
    ],
    response_model=ApiResponse[None],
)
async def revoke(
    payload: IdsRequest,
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[None]:
    await MsgAnnouncementService(db).revoke(payload)
    return success()


@admin_router.post(
    "/message/announcements/pin",
    dependencies=[
        Depends(require_account_type(AccountType.ADMIN)),
        Depends(require_permission("message:announcement:pin")),
    ],
    response_model=ApiResponse[None],
)
async def pin(
    payload: PinAnnouncementRequest,
    db: Annotated[AsyncSession, Depends(get_db_session)],
) -> ApiResponse[None]:
    await MsgAnnouncementService(db).pin(payload)
    return success()


# ==================== Current-User Routes ====================

def register_current_user_routes():
    """Register announcement routes for the current authenticated user."""

    @admin_router.get(
        "/message/announcements/my-page",
        dependencies=[Depends(require_account_type(AccountType.ADMIN))],
        response_model=ApiResponse[PageData[MsgAnnouncementSchema]],
    )
    @portal_router.get(
        "/message/announcements/my-page",
        dependencies=[Depends(require_account_type(AccountType.PORTAL))],
        response_model=ApiResponse[PageData[MsgAnnouncementSchema]],
    )
    async def my_page(
        db: Annotated[AsyncSession, Depends(get_db_session)],
        session: Annotated[SessionPayload, Depends(get_current_session)],
        query: Annotated[MyAnnouncementPageQuery, Depends()],
    ) -> ApiResponse[PageData[MsgAnnouncementSchema]]:
        return success(await MsgAnnouncementService(db).page_my_announcements(query, session))

    @admin_router.get(
        "/message/announcements/my-detail",
        dependencies=[Depends(require_account_type(AccountType.ADMIN))],
        response_model=ApiResponse[MsgAnnouncementSchema],
    )
    @portal_router.get(
        "/message/announcements/my-detail",
        dependencies=[Depends(require_account_type(AccountType.PORTAL))],
        response_model=ApiResponse[MsgAnnouncementSchema],
    )
    async def my_detail(
        query: Annotated[IdQuery, Depends()],
        db: Annotated[AsyncSession, Depends(get_db_session)],
        session: Annotated[SessionPayload, Depends(get_current_session)],
    ) -> ApiResponse[MsgAnnouncementSchema]:
        return success(await MsgAnnouncementService(db).my_detail(query, session))

    @admin_router.get(
        "/message/announcements/unread-count",
        dependencies=[Depends(require_account_type(AccountType.ADMIN))],
        response_model=ApiResponse[int],
    )
    @portal_router.get(
        "/message/announcements/unread-count",
        dependencies=[Depends(require_account_type(AccountType.PORTAL))],
        response_model=ApiResponse[int],
    )
    async def unread_count(
        db: Annotated[AsyncSession, Depends(get_db_session)],
        session: Annotated[SessionPayload, Depends(get_current_session)],
    ) -> ApiResponse[int]:
        return success(await MsgAnnouncementService(db).count_unread(session))

    @admin_router.post(
        "/message/announcements/read",
        dependencies=[Depends(require_account_type(AccountType.ADMIN))],
        response_model=ApiResponse[None],
    )
    @portal_router.post(
        "/message/announcements/read",
        dependencies=[Depends(require_account_type(AccountType.PORTAL))],
        response_model=ApiResponse[None],
    )
    async def read(
        payload: AnnouncementReadRequest,
        db: Annotated[AsyncSession, Depends(get_db_session)],
        session: Annotated[SessionPayload, Depends(get_current_session)],
    ) -> ApiResponse[None]:
        await MsgAnnouncementService(db).mark_read(payload, session)
        return success()

    @admin_router.post(
        "/message/announcements/read-all",
        dependencies=[Depends(require_account_type(AccountType.ADMIN))],
        response_model=ApiResponse[None],
    )
    @portal_router.post(
        "/message/announcements/read-all",
        dependencies=[Depends(require_account_type(AccountType.PORTAL))],
        response_model=ApiResponse[None],
    )
    async def read_all(
        db: Annotated[AsyncSession, Depends(get_db_session)],
        session: Annotated[SessionPayload, Depends(get_current_session)],
    ) -> ApiResponse[None]:
        await MsgAnnouncementService(db).mark_all_read(session)
        return success()


register_current_user_routes()
