"""
Generated by HEI code generator.
Author: Charlie
Generated at: 2026-07-23 16:28:51
"""

from datetime import datetime, timezone

from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config.enums import AccountType
from app.core.response.pagination import PageData, build_page
from app.core.schema.base import IdQuery, IdsRequest, to_schema, to_schema_list
from app.core.security.session import SessionPayload
from app.modules.user.utils.profile import get_profiles_batch
from app.platform.db.transaction import transactional
from app.modules.message.announcement.repository import (
    MsgAnnouncementRepository,
)
from app.modules.message.announcement.schema import (
    AnnouncementReadRequest,
    MsgAnnouncementAdminPageQuery,
    MsgAnnouncementCreateRequest,
    MsgAnnouncementSchema,
    MsgAnnouncementUpdateRequest,
    MyAnnouncementPageQuery,
    PinAnnouncementRequest,
)
from app.modules.message.enums import AnnouncementStatus


class MsgAnnouncementService:
    def __init__(self, db: AsyncSession):
        self.db = db
        self.repo = MsgAnnouncementRepository(db)

    async def create(self, payload: MsgAnnouncementCreateRequest) -> None:
        async with transactional(self.db):
            data = payload.model_dump()
            status = str(data.get("status") or AnnouncementStatus.DRAFT.value).upper()
            if status in {"ENABLED", "ENABLE"}:
                status = AnnouncementStatus.DRAFT.value
            if status not in {
                AnnouncementStatus.DRAFT.value,
                AnnouncementStatus.PUBLISHED.value,
                AnnouncementStatus.REVOKED.value,
            }:
                status = AnnouncementStatus.DRAFT.value
            data["status"] = status
            if status == AnnouncementStatus.PUBLISHED.value and not data.get("publish_at"):
                data["publish_at"] = datetime.now(timezone.utc)
            await self.repo.create(MsgAnnouncementCreateRequest(**data))

    async def update(self, payload: MsgAnnouncementUpdateRequest) -> None:
        async with transactional(self.db):
            await self.repo.update(payload)

    async def delete(self, payload: IdsRequest) -> None:
        async with transactional(self.db):
            await self.repo.delete_many(payload.ids)

    async def detail(self, query: IdQuery) -> MsgAnnouncementSchema:
        entity = await self.repo.get_required(query.id)
        schema = to_schema(MsgAnnouncementSchema, entity)
        return await self._enrich_profiles(schema)

    async def page_admin(self, query: MsgAnnouncementAdminPageQuery) -> PageData[MsgAnnouncementSchema]:
        items, total = await self.repo.page_admin(query)
        schemas = to_schema_list(MsgAnnouncementSchema, items)
        return build_page(query.pagination, total, await self._batch_enrich_profiles(schemas))

    async def publish(self, payload: IdsRequest, session: SessionPayload) -> None:
        async with transactional(self.db):
            now = datetime.now(timezone.utc)
            for entity_id in payload.ids:
                entity = await self.repo.get_required(entity_id)
                entity.status = AnnouncementStatus.PUBLISHED.value
                entity.publish_at = now
                entity.sender_account_type = str(session.account_type)
                entity.sender_account_id = session.account_id
            await self.db.flush()

    async def revoke(self, payload: IdsRequest) -> None:
        async with transactional(self.db):
            now = datetime.now(timezone.utc)
            for entity_id in payload.ids:
                entity = await self.repo.get_required(entity_id)
                entity.status = AnnouncementStatus.REVOKED.value
                entity.revoked_at = now
            await self.db.flush()

    async def pin(self, payload: PinAnnouncementRequest) -> None:
        async with transactional(self.db):
            entity = await self.repo.get_required(payload.id)
            entity.is_pinned = payload.is_pinned
            entity.pinned_until = payload.pinned_until
            await self.db.flush()

    async def page_my_announcements(
        self,
        query: MyAnnouncementPageQuery,
        session: SessionPayload,
    ) -> PageData[MsgAnnouncementSchema]:
        items, total, read_id_set = await self.repo.page_my_announcements(
            query,
            str(session.account_type),
            session.account_id,
        )
        schemas = [
            _build_announcement_schema(item, read_id_set)
            for item in items
        ]
        return build_page(query.pagination, total, schemas)

    async def page_portal_list(
        self,
        query: MyAnnouncementPageQuery,
        session: SessionPayload | None = None,
    ) -> PageData[MsgAnnouncementSchema]:
        """Portal 公开已发布列表；可选登录以填充 is_read。"""
        account_type = AccountType.PORTAL.value
        account_id: str | None = None
        if session and str(session.account_type) == AccountType.PORTAL.value:
            account_type = str(session.account_type)
            account_id = session.account_id
        items, total, read_id_set = await self.repo.page_my_announcements(
            query,
            account_type,
            account_id,
        )
        schemas = [_build_announcement_schema(item, read_id_set) for item in items]
        return build_page(query.pagination, total, schemas)

    async def my_detail(self, query: IdQuery, session: SessionPayload) -> MsgAnnouncementSchema:
        async with transactional(self.db):
            await self.repo.increment_view_count(query.id)
            await self.repo.mark_read([query.id], str(session.account_type), session.account_id)
        entity = await self.repo.get_required(query.id)
        read_stmt = await self._check_read([entity.id], session)
        return _build_announcement_schema(entity, read_stmt)

    async def count_unread(self, session: SessionPayload) -> int:
        return await self.repo.count_unread(str(session.account_type), session.account_id)

    async def mark_read(self, payload: AnnouncementReadRequest, session: SessionPayload) -> None:
        async with transactional(self.db):
            await self.repo.mark_read(payload.ids, str(session.account_type), session.account_id)

    async def mark_all_read(self, session: SessionPayload) -> None:
        async with transactional(self.db):
            await self.repo.mark_all_read(str(session.account_type), session.account_id)

    async def _check_read(self, announcement_ids: list[str], session: SessionPayload) -> set[str]:
        """Batch check which announcement ids are read for a given session."""
        if not announcement_ids:
            return set()
        from sqlalchemy import select
        from app.modules.message.announcement.model import MsgAnnouncementRead
        stmt = select(MsgAnnouncementRead.announcement_id).where(
            MsgAnnouncementRead.announcement_id.in_(announcement_ids),
            MsgAnnouncementRead.account_type == str(session.account_type),
            MsgAnnouncementRead.account_id == session.account_id,
        )
        rows = list((await self.db.execute(stmt)).scalars().all())
        return set(rows)


    async def _enrich_profiles(self, schema: MsgAnnouncementSchema) -> MsgAnnouncementSchema:
        ids = []
        if schema.created_by:
            ids.append(schema.created_by)
        if schema.updated_by:
            ids.append(schema.updated_by)
        if not ids:
            return schema
        profiles = await get_profiles_batch(self.db, AccountType.ADMIN, ids)
        if schema.created_by and schema.created_by in profiles:
            schema.created_name = profiles[schema.created_by].name
        if schema.updated_by and schema.updated_by in profiles:
            schema.updated_name = profiles[schema.updated_by].name
        return schema

    async def _batch_enrich_profiles(self, schemas: list[MsgAnnouncementSchema]) -> list[MsgAnnouncementSchema]:
        all_ids = set()
        for schema in schemas:
            if schema.created_by:
                all_ids.add(schema.created_by)
            if schema.updated_by:
                all_ids.add(schema.updated_by)
        if not all_ids:
            return schemas
        profiles = await get_profiles_batch(self.db, AccountType.ADMIN, list(all_ids))
        for schema in schemas:
            if schema.created_by and schema.created_by in profiles:
                schema.created_name = profiles[schema.created_by].name
            if schema.updated_by and schema.updated_by in profiles:
                schema.updated_name = profiles[schema.updated_by].name
        return schemas


def _build_announcement_schema(item, read_id_set: set[str]) -> MsgAnnouncementSchema:
    schema = to_schema(MsgAnnouncementSchema, item)
    schema.is_read = item.id in read_id_set
    return schema
