""" Author: Charlie """

from typing import Protocol, runtime_checkable

from app.platform.storage.config import StorageConfig


@runtime_checkable
class ConfigReaderProtocol(Protocol):
    async def load_all(self) -> None: ...
    async def reload(self) -> None: ...
    @property
    def version(self) -> int: ...
    def get(self, key: str, default: str | None = None) -> str | None: ...
    def get_int(self, key: str, default: int = 0) -> int: ...
    def get_bool(self, key: str, default: bool = False) -> bool: ...
    def get_list(self, key: str, default: list[str] | None = None) -> list[str]: ...
    def get_active_storage(self) -> dict | None: ...
    def get_default_storage(self) -> StorageConfig | None: ...
    def get_storage_config(self, config_id: str | None = None) -> StorageConfig | None: ...
    def list_storage_configs(self) -> list[StorageConfig]: ...
