""" Author: Charlie

从当前 codegen 模板重新生成 biz/cg_test_* 模块。
"""
from __future__ import annotations

from pathlib import Path

from app.modules.sys.codegen.apply import apply_preview_files
from app.modules.sys.codegen.model import SysCodegenField, SysCodegenPlan
from app.modules.sys.codegen.schema import CodegenPreviewFile
from app.modules.sys.codegen.templates import render_files

ROOT = Path(__file__).resolve().parents[2]
AUDIT = {"created_at", "created_by", "updated_at", "updated_by", "owner_dept_id"}


def field(
    *,
    column_name: str,
    column_comment: str,
    python_type: str,
    db_type: str,
    is_primary_key: bool = False,
    is_nullable: bool = True,
    is_required: bool = False,
    show_in_query: bool = False,
    query_operator: str | None = "LIKE",
    max_length: int | None = 64,
    form_widget: str | None = None,
    dict_code: str | None = None,
    table_role: str = "MAIN",
    sort: int = 10,
    show_in_table: bool = True,
    show_in_form: bool | None = None,
    show_in_detail: bool = True,
) -> SysCodegenField:
    if form_widget is None:
        if python_type == "datetime":
            form_widget = "datetime"
        elif python_type in {"dict", "dict[str, Any]"} or "json" in db_type:
            form_widget = "textarea"
        elif python_type == "bool":
            form_widget = "switch"
        elif python_type in {"int", "float"}:
            form_widget = "number"
        elif "text" in db_type:
            form_widget = "textarea"
        else:
            form_widget = "input"
    if show_in_form is None:
        show_in_form = not is_primary_key and column_name not in AUDIT
    if is_primary_key:
        is_nullable = False
        is_required = True
        show_in_form = False
        show_in_query = False
    if column_name in AUDIT:
        show_in_form = False
        show_in_query = False
        show_in_table = False
    ts_map = {
        "str": "string",
        "int": "number",
        "float": "number",
        "bool": "boolean",
        "datetime": "string",
        "dict": "Record<string, any>",
        "dict[str, Any]": "Record<string, any>",
    }
    return SysCodegenField(
        id=f"{table_role}:{column_name}",
        plan_id="regen",
        table_role=table_role,
        column_name=column_name,
        column_comment=column_comment,
        db_type=db_type,
        python_type="dict" if python_type.startswith("dict") else python_type,
        typescript_type=ts_map.get(python_type, "string"),
        form_widget=form_widget,
        dict_code=dict_code,
        query_operator=query_operator if show_in_query else None,
        show_in_table=show_in_table,
        show_in_form=show_in_form,
        show_in_detail=show_in_detail,
        show_in_query=show_in_query,
        is_primary_key=is_primary_key,
        is_required=is_required,
        is_unique=False,
        is_nullable=is_nullable,
        max_length=max_length,
        sort=sort,
    )


def plan(**kw) -> SysCodegenPlan:
    defaults = dict(
        id="regen",
        name="regen",
        author="Charlie",
        description=None,
        resource_module_id=None,
        parent_resource_id=None,
        icon=None,
        sort=99,
        tree_parent_field=None,
        tree_label_field=None,
        sub_table=None,
        sub_pk=None,
        sub_foreign_key=None,
        sub_entity_name=None,
        sub_business_name=None,
    )
    defaults.update(kw)
    return SysCodegenPlan(**defaults)


def build_modules() -> list[tuple[SysCodegenPlan, list[SysCodegenField], list[SysCodegenField]]]:
    activity_fields = [
        field(
            column_name="id",
            column_comment="主键",
            python_type="str",
            db_type="varchar(64)",
            is_primary_key=True,
            sort=1,
        ),
        field(
            column_name="code",
            column_comment="活动编码",
            python_type="str",
            db_type="varchar(64)",
            is_nullable=False,
            is_required=True,
            show_in_query=True,
            sort=10,
        ),
        field(
            column_name="name",
            column_comment="活动名称",
            python_type="str",
            db_type="varchar(120)",
            is_nullable=False,
            is_required=True,
            show_in_query=True,
            max_length=120,
            sort=20,
        ),
        field(
            column_name="category",
            column_comment="活动分类",
            python_type="str",
            db_type="varchar(32)",
            show_in_query=True,
            max_length=32,
            sort=30,
        ),
        field(
            column_name="type",
            column_comment="活动类型",
            python_type="str",
            db_type="varchar(32)",
            is_nullable=False,
            is_required=True,
            show_in_query=True,
            max_length=32,
            sort=40,
        ),
        field(
            column_name="status",
            column_comment="状态",
            python_type="str",
            db_type="varchar(32)",
            is_nullable=False,
            is_required=True,
            show_in_query=True,
            query_operator="EQ",
            max_length=32,
            sort=50,
        ),
        field(
            column_name="cover_url",
            column_comment="封面地址",
            python_type="str",
            db_type="varchar(512)",
            max_length=512,
            sort=60,
        ),
        field(
            column_name="description",
            column_comment="活动描述",
            python_type="str",
            db_type="text",
            max_length=None,
            sort=70,
        ),
        field(
            column_name="start_at",
            column_comment="开始时间",
            python_type="datetime",
            db_type="timestamptz",
            is_nullable=False,
            is_required=True,
            max_length=None,
            sort=80,
        ),
        field(
            column_name="end_at",
            column_comment="结束时间",
            python_type="datetime",
            db_type="timestamptz",
            max_length=None,
            sort=90,
        ),
        field(
            column_name="max_participants",
            column_comment="最大参与人数",
            python_type="int",
            db_type="integer",
            is_nullable=False,
            is_required=True,
            max_length=None,
            sort=100,
        ),
        field(
            column_name="price",
            column_comment="报名费用",
            python_type="float",
            db_type="numeric",
            is_nullable=False,
            is_required=True,
            max_length=None,
            sort=110,
        ),
        field(
            column_name="is_public",
            column_comment="是否公开",
            python_type="bool",
            db_type="boolean",
            is_nullable=False,
            is_required=True,
            max_length=None,
            sort=120,
        ),
        field(
            column_name="need_approval",
            column_comment="是否需要审批",
            python_type="bool",
            db_type="boolean",
            is_nullable=False,
            is_required=True,
            max_length=None,
            sort=130,
        ),
        field(
            column_name="rule_config",
            column_comment="规则配置",
            python_type="dict",
            db_type="jsonb",
            is_nullable=False,
            is_required=True,
            max_length=None,
            sort=140,
        ),
        field(
            column_name="extra",
            column_comment="扩展信息",
            python_type="dict",
            db_type="jsonb",
            max_length=None,
            sort=150,
        ),
        field(
            column_name="created_at",
            column_comment="创建时间",
            python_type="datetime",
            db_type="timestamptz",
            max_length=None,
            sort=900,
        ),
        field(
            column_name="created_by",
            column_comment="创建人",
            python_type="str",
            db_type="varchar(64)",
            sort=910,
        ),
        field(
            column_name="updated_at",
            column_comment="更新时间",
            python_type="datetime",
            db_type="timestamptz",
            max_length=None,
            sort=920,
        ),
        field(
            column_name="updated_by",
            column_comment="更新人",
            python_type="str",
            db_type="varchar(64)",
            sort=930,
        ),
    ]
    catalog_fields = [
        field(
            column_name="id",
            column_comment="主键",
            python_type="str",
            db_type="varchar(64)",
            is_primary_key=True,
            sort=1,
        ),
        field(
            column_name="parent_id",
            column_comment="父级ID",
            python_type="str",
            db_type="varchar(64)",
            sort=10,
        ),
        field(
            column_name="code",
            column_comment="目录编码",
            python_type="str",
            db_type="varchar(64)",
            is_nullable=False,
            is_required=True,
            show_in_query=True,
            sort=20,
        ),
        field(
            column_name="name",
            column_comment="目录名称",
            python_type="str",
            db_type="varchar(120)",
            is_nullable=False,
            is_required=True,
            show_in_query=True,
            max_length=120,
            sort=30,
        ),
        field(
            column_name="category",
            column_comment="目录分类",
            python_type="str",
            db_type="varchar(32)",
            show_in_query=True,
            max_length=32,
            sort=40,
        ),
        field(
            column_name="status",
            column_comment="状态",
            python_type="str",
            db_type="varchar(32)",
            is_nullable=False,
            is_required=True,
            show_in_query=True,
            query_operator="EQ",
            max_length=32,
            sort=50,
        ),
        field(
            column_name="sort",
            column_comment="排序",
            python_type="int",
            db_type="integer",
            is_nullable=False,
            is_required=True,
            max_length=None,
            sort=60,
        ),
        field(
            column_name="is_visible",
            column_comment="是否显示",
            python_type="bool",
            db_type="boolean",
            is_nullable=False,
            is_required=True,
            max_length=None,
            sort=70,
        ),
        field(
            column_name="icon",
            column_comment="图标",
            python_type="str",
            db_type="varchar(128)",
            max_length=128,
            sort=80,
        ),
        field(
            column_name="description",
            column_comment="描述",
            python_type="str",
            db_type="text",
            max_length=None,
            sort=90,
        ),
        field(
            column_name="extra",
            column_comment="扩展信息",
            python_type="dict",
            db_type="jsonb",
            is_nullable=False,
            is_required=True,
            max_length=None,
            sort=100,
        ),
        field(
            column_name="created_at",
            column_comment="创建时间",
            python_type="datetime",
            db_type="timestamptz",
            max_length=None,
            sort=900,
        ),
        field(
            column_name="created_by",
            column_comment="创建人",
            python_type="str",
            db_type="varchar(64)",
            sort=910,
        ),
        field(
            column_name="updated_at",
            column_comment="更新时间",
            python_type="datetime",
            db_type="timestamptz",
            max_length=None,
            sort=920,
        ),
        field(
            column_name="updated_by",
            column_comment="更新人",
            python_type="str",
            db_type="varchar(64)",
            sort=930,
        ),
    ]
    order_fields = [
        field(
            column_name="id",
            column_comment="主键",
            python_type="str",
            db_type="varchar(64)",
            is_primary_key=True,
            sort=1,
        ),
        field(
            column_name="order_no",
            column_comment="订单号",
            python_type="str",
            db_type="varchar(64)",
            is_nullable=False,
            is_required=True,
            sort=10,
        ),
        field(
            column_name="name",
            column_comment="订单名称",
            python_type="str",
            db_type="varchar(120)",
            is_nullable=False,
            is_required=True,
            show_in_query=True,
            max_length=120,
            sort=20,
        ),
        field(
            column_name="customer_name",
            column_comment="客户名称",
            python_type="str",
            db_type="varchar(120)",
            is_nullable=False,
            is_required=True,
            max_length=120,
            sort=30,
        ),
        field(
            column_name="customer_phone",
            column_comment="客户手机号",
            python_type="str",
            db_type="varchar(32)",
            max_length=32,
            sort=40,
        ),
        field(
            column_name="status",
            column_comment="状态",
            python_type="str",
            db_type="varchar(32)",
            is_nullable=False,
            is_required=True,
            show_in_query=True,
            query_operator="EQ",
            max_length=32,
            sort=50,
        ),
        field(
            column_name="type",
            column_comment="订单类型",
            python_type="str",
            db_type="varchar(32)",
            is_nullable=False,
            is_required=True,
            show_in_query=True,
            max_length=32,
            sort=60,
        ),
        field(
            column_name="ordered_at",
            column_comment="下单时间",
            python_type="datetime",
            db_type="timestamptz",
            is_nullable=False,
            is_required=True,
            max_length=None,
            sort=70,
        ),
        field(
            column_name="paid_at",
            column_comment="支付时间",
            python_type="datetime",
            db_type="timestamptz",
            max_length=None,
            sort=80,
        ),
        field(
            column_name="total_amount",
            column_comment="订单金额",
            python_type="float",
            db_type="numeric",
            is_nullable=False,
            is_required=True,
            max_length=None,
            sort=90,
        ),
        field(
            column_name="item_count",
            column_comment="商品数量",
            python_type="int",
            db_type="integer",
            is_nullable=False,
            is_required=True,
            max_length=None,
            sort=100,
        ),
        field(
            column_name="need_invoice",
            column_comment="是否开票",
            python_type="bool",
            db_type="boolean",
            is_nullable=False,
            is_required=True,
            max_length=None,
            sort=110,
        ),
        field(
            column_name="invoice_config",
            column_comment="发票配置",
            python_type="dict",
            db_type="jsonb",
            is_nullable=False,
            is_required=True,
            max_length=None,
            sort=120,
        ),
        field(
            column_name="remark",
            column_comment="备注",
            python_type="str",
            db_type="text",
            max_length=None,
            sort=130,
        ),
        field(
            column_name="extra",
            column_comment="扩展信息",
            python_type="dict",
            db_type="jsonb",
            max_length=None,
            sort=140,
        ),
        field(
            column_name="created_at",
            column_comment="创建时间",
            python_type="datetime",
            db_type="timestamptz",
            max_length=None,
            sort=900,
        ),
        field(
            column_name="created_by",
            column_comment="创建人",
            python_type="str",
            db_type="varchar(64)",
            sort=910,
        ),
        field(
            column_name="updated_at",
            column_comment="更新时间",
            python_type="datetime",
            db_type="timestamptz",
            max_length=None,
            sort=920,
        ),
        field(
            column_name="updated_by",
            column_comment="更新人",
            python_type="str",
            db_type="varchar(64)",
            sort=930,
        ),
    ]
    order_item_fields = [
        field(
            table_role="SUB",
            column_name="id",
            column_comment="主键",
            python_type="str",
            db_type="varchar(64)",
            is_primary_key=True,
            sort=1,
        ),
        field(
            table_role="SUB",
            column_name="order_id",
            column_comment="订单ID",
            python_type="str",
            db_type="varchar(64)",
            is_nullable=False,
            is_required=True,
            show_in_query=True,
            query_operator="EQ",
            sort=10,
        ),
        field(
            table_role="SUB",
            column_name="sku_code",
            column_comment="SKU编码",
            python_type="str",
            db_type="varchar(64)",
            is_nullable=False,
            is_required=True,
            sort=20,
        ),
        field(
            table_role="SUB",
            column_name="name",
            column_comment="商品名称",
            python_type="str",
            db_type="varchar(120)",
            is_nullable=False,
            is_required=True,
            show_in_query=True,
            max_length=120,
            sort=30,
        ),
        field(
            table_role="SUB",
            column_name="category",
            column_comment="商品分类",
            python_type="str",
            db_type="varchar(32)",
            show_in_query=True,
            max_length=32,
            sort=40,
        ),
        field(
            table_role="SUB",
            column_name="status",
            column_comment="状态",
            python_type="str",
            db_type="varchar(32)",
            is_nullable=False,
            is_required=True,
            show_in_query=True,
            query_operator="EQ",
            max_length=32,
            sort=50,
        ),
        field(
            table_role="SUB",
            column_name="quantity",
            column_comment="数量",
            python_type="int",
            db_type="integer",
            is_nullable=False,
            is_required=True,
            max_length=None,
            sort=60,
        ),
        field(
            table_role="SUB",
            column_name="unit_price",
            column_comment="单价",
            python_type="float",
            db_type="numeric",
            is_nullable=False,
            is_required=True,
            max_length=None,
            sort=70,
        ),
        field(
            table_role="SUB",
            column_name="shipped_at",
            column_comment="发货时间",
            python_type="datetime",
            db_type="timestamptz",
            max_length=None,
            sort=80,
        ),
        field(
            table_role="SUB",
            column_name="is_gift",
            column_comment="是否赠品",
            python_type="bool",
            db_type="boolean",
            is_nullable=False,
            is_required=True,
            max_length=None,
            sort=90,
        ),
        field(
            table_role="SUB",
            column_name="item_config",
            column_comment="明细配置",
            python_type="dict",
            db_type="jsonb",
            is_nullable=False,
            is_required=True,
            max_length=None,
            sort=100,
        ),
        field(
            table_role="SUB",
            column_name="remark",
            column_comment="备注",
            python_type="str",
            db_type="text",
            max_length=None,
            sort=110,
        ),
        field(
            table_role="SUB",
            column_name="extra",
            column_comment="扩展信息",
            python_type="dict",
            db_type="jsonb",
            max_length=None,
            sort=120,
        ),
        field(
            table_role="SUB",
            column_name="created_at",
            column_comment="创建时间",
            python_type="datetime",
            db_type="timestamptz",
            max_length=None,
            sort=900,
        ),
        field(
            table_role="SUB",
            column_name="created_by",
            column_comment="创建人",
            python_type="str",
            db_type="varchar(64)",
            sort=910,
        ),
        field(
            table_role="SUB",
            column_name="updated_at",
            column_comment="更新时间",
            python_type="datetime",
            db_type="timestamptz",
            max_length=None,
            sort=920,
        ),
        field(
            table_role="SUB",
            column_name="updated_by",
            column_comment="更新人",
            python_type="str",
            db_type="varchar(64)",
            sort=930,
        ),
    ]
    kc_fields = [
        field(
            column_name="id",
            column_comment="主键",
            python_type="str",
            db_type="varchar(64)",
            is_primary_key=True,
            sort=1,
        ),
        field(
            column_name="parent_id",
            column_comment="父级ID",
            python_type="str",
            db_type="varchar(64)",
            sort=10,
        ),
        field(
            column_name="code",
            column_comment="分类编码",
            python_type="str",
            db_type="varchar(64)",
            is_nullable=False,
            is_required=True,
            show_in_query=True,
            sort=20,
        ),
        field(
            column_name="name",
            column_comment="分类名称",
            python_type="str",
            db_type="varchar(120)",
            is_nullable=False,
            is_required=True,
            show_in_query=True,
            max_length=120,
            sort=30,
        ),
        field(
            column_name="status",
            column_comment="状态",
            python_type="str",
            db_type="varchar(32)",
            is_nullable=False,
            is_required=True,
            show_in_query=True,
            query_operator="EQ",
            max_length=32,
            sort=40,
        ),
        field(
            column_name="sort",
            column_comment="排序",
            python_type="int",
            db_type="integer",
            is_nullable=False,
            is_required=True,
            max_length=None,
            sort=50,
        ),
        field(
            column_name="is_visible",
            column_comment="是否显示",
            python_type="bool",
            db_type="boolean",
            is_nullable=False,
            is_required=True,
            max_length=None,
            sort=60,
        ),
        field(
            column_name="description",
            column_comment="描述",
            python_type="str",
            db_type="text",
            max_length=None,
            sort=70,
        ),
        field(
            column_name="extra",
            column_comment="扩展信息",
            python_type="dict",
            db_type="jsonb",
            is_nullable=False,
            is_required=True,
            max_length=None,
            sort=80,
        ),
        field(
            column_name="created_at",
            column_comment="创建时间",
            python_type="datetime",
            db_type="timestamptz",
            max_length=None,
            sort=900,
        ),
        field(
            column_name="created_by",
            column_comment="创建人",
            python_type="str",
            db_type="varchar(64)",
            sort=910,
        ),
        field(
            column_name="updated_at",
            column_comment="更新时间",
            python_type="datetime",
            db_type="timestamptz",
            max_length=None,
            sort=920,
        ),
        field(
            column_name="updated_by",
            column_comment="更新人",
            python_type="str",
            db_type="varchar(64)",
            sort=930,
        ),
    ]
    doc_fields = [
        field(
            table_role="SUB",
            column_name="id",
            column_comment="主键",
            python_type="str",
            db_type="varchar(64)",
            is_primary_key=True,
            sort=1,
        ),
        field(
            table_role="SUB",
            column_name="category_id",
            column_comment="分类ID",
            python_type="str",
            db_type="varchar(64)",
            is_nullable=False,
            is_required=True,
            show_in_query=True,
            query_operator="EQ",
            sort=10,
        ),
        field(
            table_role="SUB",
            column_name="code",
            column_comment="文档编码",
            python_type="str",
            db_type="varchar(64)",
            is_nullable=False,
            is_required=True,
            show_in_query=True,
            sort=20,
        ),
        field(
            table_role="SUB",
            column_name="title",
            column_comment="文档标题",
            python_type="str",
            db_type="varchar(160)",
            is_nullable=False,
            is_required=True,
            show_in_query=True,
            max_length=160,
            sort=30,
        ),
        field(
            table_role="SUB",
            column_name="type",
            column_comment="文档类型",
            python_type="str",
            db_type="varchar(32)",
            is_nullable=False,
            is_required=True,
            show_in_query=True,
            max_length=32,
            sort=40,
        ),
        field(
            table_role="SUB",
            column_name="status",
            column_comment="状态",
            python_type="str",
            db_type="varchar(32)",
            is_nullable=False,
            is_required=True,
            show_in_query=True,
            query_operator="EQ",
            max_length=32,
            sort=50,
        ),
        field(
            table_role="SUB",
            column_name="summary",
            column_comment="摘要",
            python_type="str",
            db_type="varchar(512)",
            max_length=512,
            sort=60,
        ),
        field(
            table_role="SUB",
            column_name="content",
            column_comment="正文内容",
            python_type="str",
            db_type="text",
            max_length=None,
            sort=70,
        ),
        field(
            table_role="SUB",
            column_name="author",
            column_comment="作者",
            python_type="str",
            db_type="varchar(64)",
            sort=80,
        ),
        field(
            table_role="SUB",
            column_name="published_at",
            column_comment="发布时间",
            python_type="datetime",
            db_type="timestamptz",
            max_length=None,
            sort=90,
        ),
        field(
            table_role="SUB",
            column_name="view_count",
            column_comment="浏览次数",
            python_type="int",
            db_type="integer",
            is_nullable=False,
            is_required=True,
            max_length=None,
            sort=100,
        ),
        field(
            table_role="SUB",
            column_name="sort",
            column_comment="排序",
            python_type="int",
            db_type="integer",
            is_nullable=False,
            is_required=True,
            max_length=None,
            sort=110,
        ),
        field(
            table_role="SUB",
            column_name="is_top",
            column_comment="是否置顶",
            python_type="bool",
            db_type="boolean",
            is_nullable=False,
            is_required=True,
            max_length=None,
            sort=120,
        ),
        field(
            table_role="SUB",
            column_name="settings",
            column_comment="展示设置",
            python_type="dict",
            db_type="jsonb",
            is_nullable=False,
            is_required=True,
            max_length=None,
            sort=130,
        ),
        field(
            table_role="SUB",
            column_name="extra",
            column_comment="扩展信息",
            python_type="dict",
            db_type="jsonb",
            max_length=None,
            sort=140,
        ),
        field(
            table_role="SUB",
            column_name="created_at",
            column_comment="创建时间",
            python_type="datetime",
            db_type="timestamptz",
            max_length=None,
            sort=900,
        ),
        field(
            table_role="SUB",
            column_name="created_by",
            column_comment="创建人",
            python_type="str",
            db_type="varchar(64)",
            sort=910,
        ),
        field(
            table_role="SUB",
            column_name="updated_at",
            column_comment="更新时间",
            python_type="datetime",
            db_type="timestamptz",
            max_length=None,
            sort=920,
        ),
        field(
            table_role="SUB",
            column_name="updated_by",
            column_comment="更新人",
            python_type="str",
            db_type="varchar(64)",
            sort=930,
        ),
    ]
    return [
        (
            plan(
                name="cg_test_activity",
                gen_type="TABLE",
                main_table="cg_test_activity",
                main_pk="id",
                main_entity_name="CgTestActivity",
                main_module_path="biz/cg_test_activity",
                main_business_name="CgTestActivity",
                api_prefix="/biz/cg-test-activity",
                permission_prefix="biz:cgtestactivity",
                menu_name="CgTestActivity",
                menu_path="/biz/cg-test-activity",
                component_path="biz/cg-test-activity/index.vue",
            ),
            activity_fields,
            [],
        ),
        (
            plan(
                name="cg_test_catalog",
                gen_type="TREE",
                main_table="cg_test_catalog",
                main_pk="id",
                main_entity_name="CgTestCatalog",
                main_module_path="biz/cg_test_catalog",
                main_business_name="CgTestCatalog",
                api_prefix="/biz/cg-test-catalog",
                permission_prefix="biz:cgtestcatalog",
                menu_name="CgTestCatalog",
                menu_path="/biz/cg-test-catalog",
                component_path="biz/cg-test-catalog/index.vue",
                tree_parent_field="parent_id",
                tree_label_field="name",
            ),
            catalog_fields,
            [],
        ),
        (
            plan(
                name="cg_test_order",
                gen_type="MASTER_DETAIL",
                main_table="cg_test_order",
                main_pk="id",
                main_entity_name="CgTestOrder",
                main_module_path="biz/cg_test_order",
                main_business_name="CgTestOrder",
                api_prefix="/biz/cg-test-order",
                permission_prefix="biz:cgtestorder",
                menu_name="CgTestOrder",
                menu_path="/biz/cg-test-order",
                component_path="biz/cg-test-order/index.vue",
                sub_table="cg_test_order_item",
                sub_pk="id",
                sub_foreign_key="order_id",
                sub_entity_name="CgTestOrderItem",
                sub_business_name="CgTestOrderItem",
            ),
            order_fields,
            order_item_fields,
        ),
        (
            plan(
                name="cg_test_knowledge_category",
                gen_type="LEFT_TREE_TABLE",
                main_table="cg_test_knowledge_category",
                main_pk="id",
                main_entity_name="CgTestKnowledgeCategory",
                main_module_path="biz/cg_test_knowledge_category",
                main_business_name="CgTestKnowledgeCategory",
                api_prefix="/biz/cg-test-knowledge-category",
                permission_prefix="biz:cgtestknowledgecategory",
                menu_name="CgTestKnowledgeCategory",
                menu_path="/biz/cg-test-knowledge-category",
                component_path="biz/cg-test-knowledge-category/index.vue",
                tree_parent_field="parent_id",
                tree_label_field="name",
                sub_table="cg_test_knowledge_doc",
                sub_pk="id",
                sub_foreign_key="category_id",
                sub_entity_name="CgTestKnowledgeDoc",
                sub_business_name="CgTestKnowledgeDoc",
            ),
            kc_fields,
            doc_fields,
        ),
    ]


def _disable_test_module(
    files: list[CodegenPreviewFile], module_name: str
) -> list[CodegenPreviewFile]:
    patched: list[CodegenPreviewFile] = []
    for item in files:
        content = item.content
        if (
            item.path.endswith("/module.py")
            or item.path.endswith("\\module.py")
            or Path(item.path).name == "module.py"
        ):
            if "enabled=" not in content:
                content = content.replace(
                    f'    name="{module_name}",\n',
                    f'    name="{module_name}",\n    enabled=False,\n',
                )
        patched.append(CodegenPreviewFile(path=item.path, language=item.language, content=content))
    return patched


def main() -> None:
    written: list[str] = []
    for codegen_plan, main_fields, sub_fields in build_modules():
        module_name = codegen_plan.main_module_path.replace("/", ".")
        files = _disable_test_module(
            render_files(codegen_plan, main_fields, sub_fields), module_name
        )
        result = apply_preview_files(files, ROOT, skip_menu_sql=True)
        written.extend(result.written)
        written.extend(f"MERGED {path}" for path in result.merged)

    for orphan in (
        ROOT / "web/admin/src/views/biz/cg-test-knowledge-category/components/ChildModalDetail.vue",
        ROOT / "web/admin/src/views/biz/cg-test-knowledge-category/components/ChildModalForm.vue",
    ):
        if orphan.exists():
            orphan.unlink()
            written.append(f"DELETED {orphan.relative_to(ROOT)}")

    print(f"touched {len(written)} paths")
    for item in written:
        print(f"  {item}")


if __name__ == "__main__":
    main()
